const prompts = [
  'Mi autobiografía',
  'Yo en 3 años',
  'Yo en 5 años',
  'Yo en 10 años',
  'Mis fantasias sociales',
  'Mis fantasias espirituales',
  'Mis fantasias profesionales',
  'Mis fantasias economicas',
  'Mis fantasias romanticas',
  'Mis fantasias sexuales',
  'Mis fetiches',
  'Mi infancia',
  'Mi adolescencia',
  'Mi adultez',
  'Mi primera cita',
  'Mi última cita',
  'Mi mejor cita',
  'Mi peor cita',
  'Mi peor error',
  'Mi acierto',
  'Mi fracaso',
  'Mi logro',
  'Mi arrepentimiento',
  'Mis viajes',
  'Mis empleos',
  'Mis aventuras',
  'Mis fiestas',
  'Mis pérdidas',
  'Mis desafíos',
  'Mis mudanzas',
  'Mis miedos',
  'Mis deseos',
  'Mis principios económicos',
  'Mis principios sexuales',
  'Mis principios sociales',
  'Mis principios emocionales',
  'Mis límites económicos',
  'Mis límites sexuales',
  'Mis límites sociales',
  'Mis límites emocionales',
  'Mi decisión más difícil',
  'Mi decisión de la que más orgulloso estoy',
  'Mi renuncia',
  'Mi sacrificio',
  'Mi mayor cambio',
  'Mi punto de quiebre',
  'Mi pareja',
  'Mis parejas',
  'Mis exparejas',
  'Mi expareja que más extraño',
  'Mi amante',
  'Mi enemigo',
  'Mi rival',
  'Mi crush',
  'Mi admirador',
  'Mi amor imposible',
  'Mi confidente',
  'Mi cómplice',
  'Mi persona favorita',
  'Mi terapeuta',
  'Mi mamá',
  'Mi papá',
  'Mis hijos',
  'Mis hijas',
  'Mis hermanos',
  'Mis hermanas',
  'Mis abuelos',
  'Mis abuelas',
  'Mis tíos',
  'Mis tías',
  'Mis primos',
  'Mis primas',
  'Mi suegro',
  'Mi suegra',
  'Mis cuñados',
  'Mis cuñadas',
  'Mi mejor amigo',
  'Mi mejor amiga',
  'Mis amigos',
  'Mis amigas',
  'Mis vecinos',
  'Mis vecinas',
  'Mi jefe',
  'Mi líder',
  'Mis socios',
  'Mis socias',
  'Mis empleados',
  'Mis empleadas',
  'Mis clientes',
  'Mis clientas',
  'Mis compañeros de trabajo',
  'Mis compañeras de trabajo',
  'Mis profesores',
  'Mis profesoras',
  'Mis alumnos',
  'Mis alumnas',
  'Mis mentores',
  'Mis mentoras',
  'Mi sexualidad',
  'Mi dinero',
  'Mi fidelidad',
  'Mi familia',
  'Mi trabajo',
  'Mi salud',
  'Mi cuerpo',
  'Mi mente',
  'Mi rutina',
  'Mi deporte',
  'Mi arte',
  'Mi talento',
  'Mi vicio',
  'Mi debilidad',
  'Mi fortaleza',
  'Mi yo deseado',
  'Mi cuerpo deseado',
  'Mi mente deseada',
  'Mi vida deseada',
  'Mi propósito',
  'Mi proyecto de vida',
  'Mi futuro',
  'Mi legado',
  'Mi relación con la ciencia',
  'Mi relación con la historia',
  'Mi relación con la educación',
  'Mi relación con la medicina',
  'Mi relación con la tecnología',
  'Mi relación con la economía',
  'Mi relación con la política',
  'Mi relación con la religión',
  'Mi relación con la geografía',
  'Mi relación con la filosofía',
  'Mi relación con la psicología',
  'Mi relación con el derecho',
  'Mi relación con las finanzas',
  'Mi relación con el emprendimiento',
  'Mi relación con el liderazgo',
  'Mi relación con la comunicación',
  'Mi relación con el arte',
  'Mi relación con la música',
  'Mi relación con el deporte',
  'Mi relación con la gastronomía',
  'Mi relación con la agricultura',
  'Mi relación con el medio ambiente',
  'Mi relación con los idiomas',
  'Mi relación con la programación',
  'Mi relación con la inteligencia artificial',
  'Mi relación con las inversiones',
  'Mi mejor consejo',
  'Mi prototipo físico de pareja',
  'Mi prototipo de personalidad de pareja',
  'Mi comida',
  'Mi música',
  'Mi película',
  'Mi serie',
  'Mi libro',
  'Mi color',
  'Mi estilo',
  'Mi hogar',
  'Mi ciudad',
  'Mi casa',
  'Mi habitación',
  'Mi mascota',
  'Mi proyecto',
  'Mi comunidad',
  'Mi invento',
  'Mi Dios',
  'Mi Diablo',
  'Mi bien',
  'Mi mal',
  'Mi creencia',
  'Mi religión',
  'Mi política',
  'Mi ángel',
  'Mi demonio',
  'Mi pecado',
  'Mis ídolos',
]

const fields = [
  {
    key: 'revelation',
    label: 'Redacción personal',
    type: 'textarea',
    placeholder: 'Escribe tu revelación personal sobre esta tarjeta',
  },
]

const writingExamples = {
  'Mi autobiografía': `Ejemplo: Mi nombre es Andrés Martínez. Nací en Medellín el 14 de mayo de 1994. Viví allí hasta 2008, luego me mudé con mi familia a Bogotá, donde terminé el colegio y empecé a trabajar. En 2016 cambié de ciudad otra vez, esta vez por decisión propia, y desde entonces mi vida ha estado marcada por independencia, aprendizaje y varios comienzos difíciles.`,
  'Yo en 3 años': `Ejemplo: En tres años quiero tener ahorrados 40 millones de pesos, no deber tarjetas de crédito, haber comprado una moto o dar la cuota inicial de un apartamento pequeño. También me gustaría estar trabajando como coordinador comercial o tener activo un negocio de ropa y tenis que venda al menos 8 millones mensuales.`,
  'Yo en 5 años': `Ejemplo: En cinco años deseo vivir en una casa propia o estar pagando un apartamento de dos habitaciones. Me gustaría estar casado o en una relación estable, tener un fondo de emergencia de 12 meses y ganar mínimo 12 millones mensuales entre empleo, negocio e inversiones.`,
  'Yo en 10 años': `Ejemplo: En diez años quiero tener una familia formada, una casa terminada de pagar o muy avanzada, un vehículo propio y un negocio que no dependa solo de mi presencia diaria. También quisiera viajar una vez al año y haber ayudado a mis padres con algo concreto, como salud o vivienda.`,
  'Mis fantasias sociales': `Ejemplo: Fantaseo con llegar a una cena en un restaurante de Bogotá donde haya empresarios, artistas y amigos, y sentir que todos me reconocen por algo que construí. Me gustaría hablar sin timidez, vestir bien, hacer reír a la mesa y salir con tres invitaciones nuevas para proyectos reales.`,
  'Mis fantasias espirituales': `Ejemplo: Fantaseo con pasar una semana en una finca sin celular, despertarme a las 5:30 a.m., meditar, escribir y sentir que por fin entiendo qué debo soltar. Me gustaría tener una señal clara, como perdonar a alguien o dejar una culpa que llevo años cargando.`,
  'Mis fantasias profesionales': `Ejemplo: Imagino entrar a una oficina propia con mi nombre en la puerta, dirigir un equipo de 12 personas y presentar un proyecto frente a una empresa grande como Bancolombia, Rappi o Mercado Libre. Quiero que mis ideas se paguen bien y que mi criterio sea buscado, no tolerado.`,
  'Mis fantasias economicas': `Ejemplo: Fantaseo con revisar mi cuenta y ver 150 millones ahorrados, cero deudas malas y dos ingresos mensuales: mi trabajo principal y un local de ropa urbana que venda tenis importados. Me gustaría pagar un viaje familiar sin pedir cuotas ni sentir ansiedad.`,
  'Mis fantasias romanticas': `Ejemplo: Fantaseo con vivir con alguien en un apartamento luminoso, desayunar juntos los domingos, planear un viaje a Cartagena y saber que esa persona me escribe no por obligación sino porque me extraña. Quiero una relación donde hablemos de matrimonio sin miedo ni presión.`,
  'Mis fantasias sexuales': `Ejemplo: Fantaseo con una noche planeada con confianza: hotel bonito, conversación previa, límites claros y deseo mutuo sin pena. Me atrae poder decir lo que me gusta, escuchar lo que la otra persona quiere y sentir que la intimidad no es actuación sino complicidad.`,
  'Mis fetiches': `Ejemplo: Me atraen detalles muy específicos, como unas botas negras, una voz segura o una persona que tome la iniciativa sin ser brusca. No se trata solo del objeto o gesto, sino de la actitud que despierta en mí: curiosidad, tensión y ganas de dejarme llevar.`,
  'Mi infancia': `Ejemplo: Crecí en una casa pequeña del barrio San Javier. Recuerdo jugar fútbol en la calle hasta las 6 de la tarde, esconder mis cuadernos cuando sacaba mala nota y esperar a mi mamá cuando volvía del trabajo. Entre 2001 y 2006 aprendí a ser obediente, pero también a guardar muchas cosas.`,
  'Mi adolescencia': `Ejemplo: En mi adolescencia, entre los 13 y los 17 años, pasaba mucho tiempo intentando encajar. En el colegio me daba pena hablarle a quien me gustaba, me comparaba con mis compañeros y empecé a usar ropa ancha para ocultar inseguridades. También descubrí la música que todavía me acompaña.`,
  'Mi adultez': `Ejemplo: Mi adultez empezó de verdad cuando a los 22 años tuve que pagar arriendo, mercado y transporte con un sueldo de 1.200.000 pesos. Ahí entendí que quejarme no resolvía nada y que cada decisión, desde una deuda hasta una relación, tenía consecuencias concretas.`,
  'Mi primera cita': `Ejemplo: Mi primera cita fue en un centro comercial, tomando helado porque no tenía dinero para más. Llegué 20 minutos antes, ensayé temas de conversación y me puse una camisa azul que me quedaba grande. Me dio pena darle la mano, pero recuerdo que volví a casa sonriendo.`,
  'Mi última cita': `Ejemplo: Mi última cita fue un viernes por la noche en un café de Chapinero. Hablamos de trabajo, familia y relaciones pasadas. Me gustó su forma de escuchar, pero noté que evitaba responder cuando pregunté qué buscaba realmente, y eso me dejó pensando.`,
  'Mi mejor cita': `Ejemplo: Mi mejor cita fue una tarde de lluvia caminando por el centro. Entramos a una librería, compramos café barato y terminamos hablando tres horas sobre infancia, miedos y planes. No hubo lujo, pero sentí que no tenía que fingir nada.`,
  'Mi peor cita': `Ejemplo: Mi peor cita fue con alguien que pasó casi toda la cena mirando el celular y hablando de su ex. Yo había reservado mesa y me esforcé por conversar, pero a los 40 minutos ya quería irme. Me enseñó a no ignorar la incomodidad por educación.`,
  'Mi peor error': `Ejemplo: Mi peor error fue firmar como codeudor de un amigo en 2019 por 7 millones de pesos. Confié sin leer bien, él dejó de pagar y terminé asumiendo una deuda que dañó mi historial y nuestra amistad. Aprendí que querer ayudar no significa poner mi estabilidad en riesgo.`,
  'Mi acierto': `Ejemplo: Mi mayor acierto fue renunciar a un trabajo donde ganaba 2.300.000 pesos pero vivía agotado, para aceptar uno de menor salario mientras estudiaba análisis de datos. Seis meses después conseguí un cargo mejor y entendí que retroceder un paso también puede ser estrategia.`,
  'Mi fracaso': `Ejemplo: Mi fracaso más claro fue abrir una tienda virtual de camisetas en 2021 sin estudiar costos, envíos ni publicidad. Invertí 3 millones, vendí poco y quedé con inventario guardado. Me dolió, pero aprendí que una idea bonita no reemplaza un plan serio.`,
  'Mi logro': `Ejemplo: Mi logro fue terminar la universidad trabajando de día y estudiando de noche. Hubo semestres en los que dormía cuatro horas, debía mensualidades y pensé en aplazar. Cuando recibí el diploma, sentí que no era solo un papel: era prueba de resistencia.`,
  'Mi arrepentimiento': `Ejemplo: Me arrepiento de no haber visitado más a mi abuelo en 2020, cuando todavía podía conversar. Siempre decía que iría el domingo siguiente, hasta que se enfermó. Hoy me pesa haber tratado el tiempo con él como si fuera infinito.`,
  'Mis viajes': `Ejemplo: Mi viaje a Santa Marta en 2022 me mostró una versión más libre de mí. Fui con dos amigos, dormimos en un hostal barato, subimos al Tayrona y una noche terminé hablando con desconocidos sobre cambiar de vida. Volví con ganas de moverme más.`,
  'Mis empleos': `Ejemplo: Mi primer empleo fue empacando pedidos en una bodega por turnos de 10 horas. Después trabajé en call center, ventas y soporte. Cada empleo me dejó una marca: aprendí puntualidad, paciencia con clientes difíciles y la certeza de que no quiero depender toda la vida de un jefe.`,
  'Mis aventuras': `Ejemplo: Una aventura fue irme un fin de semana a Salento con 180.000 pesos, una maleta pequeña y dos personas que casi no conocía. Dormimos apretados, caminamos hasta el Valle del Cocora y terminé descubriendo que a veces necesito menos control para sentirme vivo.`,
  'Mis fiestas': `Ejemplo: Recuerdo una fiesta de diciembre en 2018 donde bailé hasta las 4 a.m., besé a alguien que me gustaba y al día siguiente desperté con culpa porque había prometido no volver a mezclar alcohol con despecho. Esa noche resume mi lado impulsivo.`,
  'Mis pérdidas': `Ejemplo: Una de mis pérdidas fue vender la bicicleta que usaba para ir al trabajo porque necesitaba pagar arriendo. No era solo un objeto: representaba independencia. Ese mes entendí lo humillante que puede sentirse perder algo pequeño cuando ya estás cansado.`,
  'Mis desafíos': `Ejemplo: Uno de mis desafíos fue vivir seis meses solo en una ciudad donde no conocía a nadie. Tenía que cocinar, trabajar, cuidar mis gastos y no llamar llorando cada noche. Aprendí a acompañarme, aunque muchos días me sentí abandonado.`,
  'Mis mudanzas': `Ejemplo: Me mudé de Medellín a Bogotá en 2008, luego a Soacha en 2014 y a Cali en 2021 por trabajo. Cada mudanza significó empacar libros, dejar amigos y aprender una nueva ruta de buses. No solo cambié de casa; cambié de versión.`,
  'Mis miedos': `Ejemplo: Me da miedo llegar a los 40 años sin casa, sin pareja estable y con deudas que me obliguen a aceptar cualquier trabajo. También me asusta enfermarme y no tener ahorros para responder. Por eso a veces soy demasiado controlador con el dinero.`,
  'Mis deseos': `Ejemplo: Deseo comprar un apartamento antes de los 35, tener una pareja con quien pueda hablar de hijos sin pánico, viajar a México y montar un negocio de ropa deportiva. También deseo algo menos visible: dormir tranquilo sin sentir que voy tarde en la vida.`,
  'Mis principios económicos': `Ejemplo: Mi principio económico principal es no endeudarme para aparentar. Prefiero usar un celular de hace tres años antes que pagar 24 cuotas por impresionar. También creo que si gano más, primero debo ahorrar, ayudar en casa y luego darme gustos.`,
  'Mis principios sexuales': `Ejemplo: Para mí no hay deseo sin consentimiento claro. No me gusta insistir si alguien duda, y prefiero hablar antes de asumir. También creo que cuidarse con preservativo y decir la verdad sobre otras relaciones es parte del respeto, no un detalle opcional.`,
  'Mis principios sociales': `Ejemplo: En lo social intento no burlarme de quien está ausente para quedar bien con el grupo. Si invito a alguien, lo incluyo; si prometo ir, aviso si no puedo. Me importan esos gestos pequeños porque muestran carácter.`,
  'Mis principios emocionales': `Ejemplo: Mi principio emocional es no castigar con silencio. Si estoy molesto, puedo pedir unas horas, pero no desaparecer tres días para manipular. También intento no decir “no pasa nada” cuando sí pasa, porque luego eso se vuelve resentimiento.`,
  'Mis límites económicos': `Ejemplo: No presto dinero que necesito para arriendo, salud o comida. Puedo ayudar con 50.000 o 100.000 pesos si puedo perderlos sin rabia, pero no vuelvo a sacar créditos para nadie ni a pagar cuentas de una pareja por miedo a que se vaya.`,
  'Mis límites sexuales': `Ejemplo: No acepto tener intimidad sin preservativo con alguien que no conozco bien, ni hacer cosas que me incomodan solo para parecer abierto. También necesito poder parar en cualquier momento sin que la otra persona se enoje o me presione.`,
  'Mis límites sociales': `Ejemplo: No me quedo en grupos donde la diversión depende de humillar a alguien. Tampoco acepto que me graben borracho, que revisen mi celular como chiste o que me obliguen a gastar dinero para no verme tacaño.`,
  'Mis límites emocionales': `Ejemplo: Mi límite emocional es no perseguir a alguien que responde cuando quiere, cancela planes sin explicación y luego vuelve como si nada. Puedo querer mucho, pero no quiero volver a vivir pendiente de una notificación para sentirme valioso.`,
  'Mi decisión más difícil': `Ejemplo: Mi decisión más difícil fue terminar una relación de cuatro años aunque ya habíamos hablado de vivir juntos. La quería, pero peleábamos cada semana, yo lloraba en silencio y entendí que casarnos habría sido convertir el miedo a quedarme solo en un contrato.`,
  'Mi decisión de la que más orgulloso estoy': `Ejemplo: La decisión de la que más orgulloso estoy fue pagar mis deudas una por una durante 18 meses. Dejé de salir, vendí mi consola y anoté cada pago en una libreta. El día que quedé en cero sentí más libertad que cuando compraba cosas.`,
  'Mi renuncia': `Ejemplo: Renuncié a un puesto en 2022 después de que mi jefe me gritara frente al equipo por tercera vez. Tenía miedo porque no había ahorrado mucho, pero preferí buscar otro empleo antes que acostumbrarme a ser tratado como si no valiera.`,
  'Mi sacrificio': `Ejemplo: Mi sacrificio fue dejar de estudiar un semestre para ayudar con los gastos de mi casa cuando mi mamá perdió el empleo. Trabajé turnos extra, pagué servicios y me atrasé en mi carrera. No me arrepiento, pero sí me dolió pausar mi propio plan.`,
  'Mi mayor cambio': `Ejemplo: Mi mayor cambio fue dejar de tomar todos los fines de semana después de una pelea familiar en 2021. Borré contactos de rumba, empecé a entrenar a las 6 a.m. y descubrí que mucha gente solo estaba cerca cuando había fiesta.`,
  'Mi punto de quiebre': `Ejemplo: Mi punto de quiebre fue una noche en la que revisé mi cuenta y tenía 18.000 pesos, tres deudas vencidas y cero ganas de levantarme al día siguiente. Ese día escribí una lista de cosas que debía cambiar porque ya no podía seguir improvisando.`,
  'Mi pareja': `Ejemplo: Mi pareja ideal no es solo alguien que me guste, sino alguien con quien pueda descansar emocionalmente. Quiero deseo, complicidad y una forma de hablar que no convierta cada diferencia en amenaza.`,
  'Mis parejas': `Ejemplo: Mis parejas han mostrado distintas versiones de mí: la que ama con miedo, la que intenta salvar, la que aprende a irse y la que todavía cree que el amor puede ser tranquilo.`,
  'Mis exparejas': `Ejemplo: Mis exparejas dejaron aprendizajes que no siempre pude ver en el momento. Algunas me mostraron mis heridas, otras mis errores, y otras simplemente una etapa que ya no me representa.`,
  'Mi expareja que más extraño': `Ejemplo: La expareja que más extraño no necesariamente fue la relación más sana. La extraño por una forma de mirarme, por una conversación pendiente o por la versión de mí que existía con ella.`,
  'Mi amante': `Ejemplo: Mi amante representa una parte intensa, secreta o contradictoria de mi historia. Escribiría qué buscaba en esa conexión, qué me dio, qué me quitó y qué verdad mía dejó al descubierto.`,
  'Mi enemigo': `Ejemplo: Mi enemigo me enseñó cosas que nadie cercano habría logrado mostrarme. En esa tensión vi mi orgullo, mi rabia, mi necesidad de defenderme y también partes de mí que no me gustó reconocer.`,
  'Mi rival': `Ejemplo: Mi rival despertó una competencia que a veces me impulsó y a veces me consumió. Compararme con esa persona me mostró mis inseguridades, mi ambición y mi deseo de ser tomado en serio.`,
  'Mi crush': `Ejemplo: Mi crush revela lo que idealizo. Me atrae una mezcla de rasgos reales e imaginados, y a veces esa ilusión habla más de mis deseos pendientes que de la persona en sí.`,
  'Mi admirador': `Ejemplo: Mi admirador me hizo sentir visto de una manera particular. A veces me halagó, otras me incomodó, y me obligó a pensar cómo recibo el deseo o la atención de alguien más.`,
  'Mi amor imposible': `Ejemplo: Mi amor imposible tuvo algo de deseo y algo de distancia. Tal vez no podía ser por tiempo, contexto o miedo, pero me mostró cuánto puedo imaginar alrededor de alguien que no tengo.`,
  'Mi confidente': `Ejemplo: Mi confidente conoce partes de mí que casi nadie ve. Con esa persona he hablado sin tanta defensa, y eso revela qué necesito para sentir confianza: escucha, discreción y ausencia de juicio.`,
  'Mi cómplice': `Ejemplo: Mi cómplice es quien entendió mi lado travieso, ambicioso o secreto sin pedirme demasiadas explicaciones. Esa relación me recuerda que también necesito juego, riesgo y una lealtad silenciosa.`,
  'Mi persona favorita': `Ejemplo: Mi persona favorita no lo es por perfección, sino por la calma que me produce. Hay alguien cuya presencia me hace sentir más humano, más liviano o más capaz de ser yo.`,
  'Mi terapeuta': `Ejemplo: Mi terapeuta representa una etapa en la que decidí mirarme con más honestidad. Hablar ahí me confrontó con patrones, heridas y preguntas que antes evitaba con ocupación o orgullo.`,
  'Mi mamá': `Ejemplo: Mi mamá influyó en mi forma de amar, preocuparme y resistir. Hay cosas que le agradezco profundamente, otras que todavía me duelen, y ambas verdades conviven cuando hablo de ella.`,
  'Mi papá': `Ejemplo: Mi papá marcó mi idea de autoridad, protección o ausencia. Escribiría sobre lo que aprendí de él, lo que me faltó y la manera en que su presencia o distancia sigue influyendo en mí.`,
  'Mis hijos': `Ejemplo: Mis hijos me enfrentan a una responsabilidad que cambia prioridades. Hablaría de lo que despiertan en mí: ternura, miedo, orgullo y la necesidad de ser una versión más consciente de mí mismo.`,
  'Mis hijas': `Ejemplo: Mis hijas me conectan con una forma de cuidado que exige presencia. Contaría qué quiero enseñarles, qué temo transmitirles y cómo ellas han cambiado mi manera de mirar el futuro.`,
  'Mis hermanos': `Ejemplo: Mis hermanos conocen una versión de mí anterior a muchas máscaras. Con ellos hay historia, competencia, protección o distancia, y esa mezcla revela mucho sobre mi forma de pertenecer.`,
  'Mis hermanas': `Ejemplo: Mis hermanas han sido espejo, refugio o conflicto en distintos momentos. Hablaría de lo que compartimos, lo que nos separó y cómo esa relación moldeó mi sensibilidad familiar.`,
  'Mis abuelos': `Ejemplo: Mis abuelos representan raíces, historias y silencios heredados. Recuerdo gestos, frases o ausencias que me enseñaron algo sobre paciencia, dureza, cariño o la forma en que una familia sobrevive.`,
  'Mis abuelas': `Ejemplo: Mis abuelas guardan una parte emocional de mi memoria. En ellas pienso cuando recuerdo cuidados, comidas, consejos o dolores antiguos que todavía influyen en lo que entiendo por hogar.`,
  'Mis tíos': `Ejemplo: Mis tíos fueron figuras cercanas o lejanas que ampliaron mi idea de familia. Algunos me enseñaron con ejemplo, otros con advertencias, y cada uno dejó una impresión distinta en mi historia.`,
  'Mis tías': `Ejemplo: Mis tías aparecen en recuerdos de cuidado, opinión, complicidad o conflicto. Hablar de ellas sería contar cómo ciertas mujeres de mi familia influyeron en mi carácter y mis formas de afecto.`,
  'Mis primos': `Ejemplo: Mis primos fueron compañeros de etapas donde la familia también era juego, comparación o alianza. Con ellos aprendí dinámicas de pertenencia que todavía recuerdo con cariño o distancia.`,
  'Mis primas': `Ejemplo: Mis primas forman parte de una memoria familiar más íntima. Hubo conversaciones, juegos o diferencias que me mostraron otras formas de crecer dentro del mismo árbol familiar.`,
  'Mi suegro': `Ejemplo: Mi suegro representa una relación donde se mezclan respeto, evaluación y familia elegida. Contaría cómo me hizo sentir entrar a ese entorno y qué aprendí sobre mí en ese vínculo.`,
  'Mi suegra': `Ejemplo: Mi suegra puede revelar mucho sobre mi forma de integrarme a una familia ajena. Hablaría de aceptación, tensión, límites y del papel que esa relación tuvo en una historia de pareja.`,
  'Mis cuñados': `Ejemplo: Mis cuñados muestran cómo vivo los vínculos que llegan por medio de alguien más. Con ellos puede haber complicidad, distancia o roce, pero también aprendizajes sobre convivencia y respeto.`,
  'Mis cuñadas': `Ejemplo: Mis cuñadas han sido parte de dinámicas familiares donde uno no siempre elige, pero sí aprende. Contaría qué lugar ocupé, qué afinidades aparecieron y qué límites fueron necesarios.`,
  'Mi mejor amigo': `Ejemplo: Mi mejor amigo conoce cosas que no suelo explicar. Esa amistad me ha dado lealtad, verdad incómoda y momentos donde pude ser vulnerable sin sentir que perdía valor.`,
  'Mi mejor amiga': `Ejemplo: Mi mejor amiga representa una confianza distinta. Con ella he podido hablar de miedo, deseo, vergüenza o alegría sin sentir que debía ordenar todo antes de decirlo.`,
  'Mis amigos': `Ejemplo: Mis amigos revelan qué tipo de compañía elijo. Algunos están para celebrar, otros para sostener, y otros me enseñaron que no toda cercanía merece el nombre de amistad.`,
  'Mis amigas': `Ejemplo: Mis amigas han influido en mi forma de escuchar, confiar y compartir. Con algunas aprendí ternura; con otras, límites. Cada una muestra una parte de mi mundo emocional.`,
  'Mis vecinos': `Ejemplo: Mis vecinos dicen mucho de mi relación con la convivencia. He tenido cercanías inesperadas, molestias pequeñas y momentos donde entendí que vivir cerca no siempre significa conocerse.`,
  'Mis vecinas': `Ejemplo: Mis vecinas aparecen en mi memoria como presencias cotidianas: saludos, rumores, ayudas o tensiones. Escribiría cómo esas relaciones pequeñas también forman una idea de comunidad.`,
  'Mi jefe': `Ejemplo: Mi jefe me mostró cómo reacciono frente a la autoridad. Dependiendo de la experiencia, aprendí obediencia, resistencia, ambición o la importancia de no entregar mi dignidad por aprobación.`,
  'Mi líder': `Ejemplo: Mi líder ideal, o el que más me marcó, me hizo entender que guiar no es imponer. Contaría cómo esa figura despertó en mí disciplina, confianza o ganas de mejorar.`,
  'Mis socios': `Ejemplo: Mis socios revelan cómo negocio confianza, riesgo y visión compartida. Con ellos he aprendido que una idea puede unir, pero el carácter de cada persona decide si algo se sostiene.`,
  'Mis socias': `Ejemplo: Mis socias han marcado mi forma de colaborar y repartir responsabilidades. Hablaría de acuerdos, desacuerdos y de lo que descubrí sobre mi manera de confiar en el criterio de otra persona.`,
  'Mis empleados': `Ejemplo: Mis empleados me obligan a pensar en responsabilidad, claridad y trato justo. Escribiría qué tipo de autoridad quiero ejercer y qué errores he cometido al dirigir o delegar.`,
  'Mis empleadas': `Ejemplo: Mis empleadas han mostrado mi forma de liderar, cuidar límites y reconocer trabajo ajeno. Contaría qué aprendí sobre respeto, comunicación y el poder que uno tiene sobre el ambiente de otros.`,
  'Mis clientes': `Ejemplo: Mis clientes me han enseñado paciencia, negociación y criterio. Algunos me impulsaron a mejorar; otros me mostraron la importancia de poner límites sin perder profesionalismo.`,
  'Mis clientas': `Ejemplo: Mis clientas han revelado cómo manejo expectativas, confianza y servicio. Contaría una experiencia donde entendí que vender o atender también implica escuchar y sostener una promesa.`,
  'Mis compañeros de trabajo': `Ejemplo: Mis compañeros de trabajo muestran cómo soy en equipo. He conocido alianzas, envidias, aprendizajes y personas que hicieron más llevadera una etapa laboral difícil.`,
  'Mis compañeras de trabajo': `Ejemplo: Mis compañeras de trabajo han sido apoyo, inspiración o desafío. Escribiría sobre dinámicas de colaboración, competencia y respeto que me enseñaron mucho sobre convivencia profesional.`,
  'Mis profesores': `Ejemplo: Mis profesores dejaron frases, exigencias o gestos que todavía recuerdo. Algunos despertaron curiosidad; otros me hicieron dudar de mí. Todos influyeron en mi relación con aprender.`,
  'Mis profesoras': `Ejemplo: Mis profesoras marcaron mi manera de mirar ciertas materias y también mi confianza. Hubo una que me exigió, otra que me escuchó y alguna que me hizo sentir capaz.`,
  'Mis alumnos': `Ejemplo: Mis alumnos me han enseñado que explicar algo exige humildad. Con ellos he visto paciencia, frustración y la responsabilidad de no apagar la curiosidad de alguien que intenta aprender.`,
  'Mis alumnas': `Ejemplo: Mis alumnas me recuerdan que enseñar también es cuidar una voz que está creciendo. Contaría una experiencia donde aprendí de sus preguntas, su esfuerzo o su manera de mirar el mundo.`,
  'Mis mentores': `Ejemplo: Mis mentores aparecieron cuando necesitaba dirección. No todos fueron suaves, pero algunos me dieron una frase, una oportunidad o una corrección que cambió mi manera de avanzar.`,
  'Mis mentoras': `Ejemplo: Mis mentoras me han mostrado caminos posibles con inteligencia y carácter. Hablaría de una mujer que me enseñó a confiar más en mi criterio y a tomarme en serio.`,
  'Mi sexualidad': `Ejemplo: Mi sexualidad ha sido una mezcla de descubrimiento, pudor, deseo y preguntas. Escribiría cómo la vivo, qué me da confianza y qué cosas todavía estoy aprendiendo a nombrar sin vergüenza.`,
  'Mi dinero': `Ejemplo: Mi dinero revela mis miedos y mis prioridades. A veces lo cuido por ansiedad, otras lo gasto para sentir libertad, y todavía aprendo a usarlo sin que defina mi valor.`,
  'Mi fidelidad': `Ejemplo: Mi fidelidad no es solo no traicionar; es decidir cómo cuido un acuerdo cuando aparece la tentación, la distancia o el aburrimiento. Contaría qué entiendo por lealtad real.`,
  'Mi familia': `Ejemplo: Mi familia es una mezcla de amor, historia, heridas y costumbres. Hay cosas que agradezco y otras que intento no repetir, porque de ahí viene mucho de mi forma de vincularme.`,
  'Mi trabajo': `Ejemplo: Mi trabajo no solo paga cuentas; también afecta mi autoestima. Escribiría qué busco en lo profesional, qué me agota y qué tipo de esfuerzo me hace sentir orgulloso.`,
  'Mi salud': `Ejemplo: Mi salud me ha obligado a escuchar señales que antes ignoraba. Contaría cómo cuido o descuido mi cuerpo, qué miedos tengo y qué aprendí cuando no pude seguir funcionando igual.`,
  'Mi cuerpo': `Ejemplo: Mi cuerpo ha sido hogar, conflicto y memoria. Hay partes que acepto, otras que critiqué demasiado, y experiencias que cambiaron la forma en que me miro y me presento.`,
  'Mi mente': `Ejemplo: Mi mente puede ser mi aliada y mi cárcel. Pienso mucho, a veces demasiado, y escribiría cómo manejo mis ideas, mis obsesiones, mis intuiciones y mis momentos de claridad.`,
  'Mi rutina': `Ejemplo: Mi rutina muestra lo que realmente priorizo, no lo que digo priorizar. Hablaría de mis mañanas, mis distracciones, mis pequeños rituales y las partes de mi día que quiero cambiar.`,
  'Mi deporte': `Ejemplo: Mi deporte me conecta con disciplina, competencia o liberación. Contaría qué siento al entrenar, qué me ha enseñado sobre mi cuerpo y qué parte de mi carácter aparece cuando me exijo.`,
  'Mi arte': `Ejemplo: Mi arte es la forma en que saco algo que no siempre sé explicar. Puede ser dibujo, música, escritura o mirada; ahí aparece una sensibilidad que en otros contextos escondo.`,
  'Mi talento': `Ejemplo: Mi talento no siempre fue evidente para mí. Alguien lo notó antes, o apareció cuando insistí en algo que disfrutaba. Escribiría cómo lo uso y qué miedo tengo de desperdiciarlo.`,
  'Mi vicio': `Ejemplo: Mi vicio revela una forma de escapar. No lo contaría solo para confesarlo, sino para explicar qué vacío, ansiedad o placer intento calmar cuando vuelvo a eso.`,
  'Mi debilidad': `Ejemplo: Mi debilidad aparece cuando algo toca una herida precisa. Puede ser aprobación, abandono, orgullo o miedo; escribiría cómo me afecta y qué estoy intentando entender de esa reacción.`,
  'Mi fortaleza': `Ejemplo: Mi fortaleza no es que nada me duela, sino que he seguido incluso con miedo. Contaría una situación donde descubrí que podía resistir más de lo que imaginaba.`,
  'Mi yo deseado': `Ejemplo: Mi yo deseado es alguien más honesto, disciplinado y tranquilo. No quiero convertirme en otra persona, sino dejar de traicionarme en decisiones pequeñas que terminan definiendo mi vida.`,
  'Mi cuerpo deseado': `Ejemplo: Mi cuerpo deseado no es solo una imagen; es sentirme cómodo habitándolo. Quiero fuerza, salud y confianza, pero también dejar de tratarme como un proyecto que nunca está terminado.`,
  'Mi mente deseada': `Ejemplo: Mi mente deseada sería más clara y menos cruel conmigo. Me gustaría pensar con profundidad sin caer en ansiedad, decidir sin tanta culpa y descansar sin sentir que pierdo tiempo.`,
  'Mi vida deseada': `Ejemplo: Mi vida deseada tiene libertad, vínculos sinceros y días que no sienta que estoy sobreviviendo. Me imagino creando, amando y trabajando desde una calma que todavía estoy construyendo.`,
  'Mi propósito': `Ejemplo: Mi propósito parece aparecer cuando siento que lo que hago puede servirle a alguien más. No lo tengo completamente resuelto, pero sé que necesito crear algo con sentido.`,
  'Mi proyecto de vida': `Ejemplo: Mi proyecto de vida combina independencia, amor y construcción. Quiero una vida donde mis decisiones económicas, afectivas y creativas apunten en la misma dirección, aunque todavía esté aprendiendo cómo lograrlo.`,
  'Mi futuro': `Ejemplo: Mi futuro me emociona y me asusta. Hay días en que lo veo amplio y otros en que lo siento incierto, pero quiero llegar ahí sin abandonar las partes más verdaderas de mí.`,
  'Mi legado': `Ejemplo: Mi legado no tendría que ser fama; me bastaría dejar una huella honesta. Quiero que algunas personas recuerden que las cuidé, que creé algo útil o que viví con intención.`,
  'Mi relación con la ciencia': `Ejemplo: Mi relación con la ciencia mezcla curiosidad y respeto. Me interesa cómo explica lo que antes parecía misterio, aunque también me recuerda que muchas certezas pueden cambiar con nueva evidencia.`,
  'Mi relación con la historia': `Ejemplo: La historia me hace sentir que no nací en el vacío. Me interesa entender de dónde vienen las ideas, las heridas y las decisiones colectivas que todavía afectan mi vida.`,
  'Mi relación con la educación': `Ejemplo: La educación para mí ha sido oportunidad y también frustración. He aprendido en aulas, errores y conversaciones; por eso no reduzco la inteligencia a diplomas, aunque valore estudiar.`,
  'Mi relación con la medicina': `Ejemplo: La medicina me despierta gratitud y preguntas. He visto cómo puede aliviar, pero también cómo una persona enferma necesita ser escuchada, no tratada solo como un caso.`,
  'Mi relación con la tecnología': `Ejemplo: La tecnología me atrae porque amplifica capacidades, pero también me inquieta cuando reemplaza presencia o criterio. La uso, la disfruto y al mismo tiempo intento no entregarle toda mi atención.`,
  'Mi relación con la economía': `Ejemplo: La economía dejó de parecerme abstracta cuando entendí cómo afecta comida, tiempo y dignidad. Me interesa porque muestra qué valoramos realmente como sociedad, incluso cuando no lo admitimos.`,
  'Mi relación con la política': `Ejemplo: La política me importa porque decide cosas íntimas aunque parezcan lejanas. Me cuesta la manipulación, pero no quiero desentenderme de temas que afectan derechos, oportunidades y convivencia.`,
  'Mi relación con la religión': `Ejemplo: La religión en mi vida ha sido pregunta, herencia o refugio según la etapa. Hay símbolos que respeto, ideas que cuestiono y experiencias que me hicieron pensar en lo sagrado.`,
  'Mi relación con la geografía': `Ejemplo: La geografía me recuerda que el lugar donde nacemos cambia oportunidades, acentos, miedos y sueños. Me interesa cómo un territorio puede formar carácter sin que uno lo note.`,
  'Mi relación con la filosofía': `Ejemplo: La filosofía me acompaña cuando una respuesta práctica no basta. Me gusta porque obliga a preguntar por sentido, libertad, muerte y verdad, aunque a veces incomode vivir con tantas preguntas.`,
  'Mi relación con la psicología': `Ejemplo: La psicología me ayudó a mirar conductas que antes juzgaba sin entender. Me interesa porque revela patrones, heridas y formas de sanar que no siempre son visibles desde afuera.`,
  'Mi relación con el derecho': `Ejemplo: El derecho me parece una forma de ordenar conflictos humanos. Me interesa cuando protege al vulnerable, pero me inquieta cuando se vuelve lenguaje frío para injusticias muy reales.`,
  'Mi relación con las finanzas': `Ejemplo: Las finanzas me enseñan que libertad también requiere orden. Me interesa aprender a decidir mejor con el dinero, no para vivir obsesionado, sino para no depender siempre de la urgencia.`,
  'Mi relación con el emprendimiento': `Ejemplo: El emprendimiento me atrae porque combina riesgo, creatividad y carácter. Me entusiasma construir algo propio, aunque sé que también exige tolerar incertidumbre, ventas, errores y soledad.`,
  'Mi relación con el liderazgo': `Ejemplo: El liderazgo para mí no es mandar más fuerte. Admiro a quien da dirección sin humillar, escucha sin perder firmeza y sabe asumir responsabilidad cuando las cosas salen mal.`,
  'Mi relación con la comunicación': `Ejemplo: La comunicación me importa porque muchas heridas nacen de lo que no se dijo bien. Estoy aprendiendo a expresar límites, deseos y desacuerdos sin esconderme ni atacar.`,
  'Mi relación con el arte': `Ejemplo: El arte me conecta con emociones que no siempre caben en una explicación. Una canción, imagen o escena puede hacerme entender algo de mí antes de poder decirlo.`,
  'Mi relación con la música': `Ejemplo: La música ordena recuerdos que yo no sabía dónde guardar. Hay canciones que me devuelven a personas, etapas y versiones mías que todavía viven en algún lugar interno.`,
  'Mi relación con el deporte': `Ejemplo: El deporte me enseña disciplina y presencia. Cuando entreno o compito, aparecen mi paciencia, mi frustración y mi manera de medir progreso sin depender solo del resultado.`,
  'Mi relación con la gastronomía': `Ejemplo: La gastronomía para mí es memoria y encuentro. Un sabor puede llevarme a una casa, una persona o una etapa, y cocinar también puede ser una forma de cuidar.`,
  'Mi relación con la agricultura': `Ejemplo: La agricultura me conecta con paciencia, tierra y origen. Me recuerda que no todo crece al ritmo que uno quiere y que detrás de cada alimento hay trabajo invisible.`,
  'Mi relación con el medio ambiente': `Ejemplo: El medio ambiente me importa porque no es un tema lejano; es el aire, el agua y el futuro. A veces me siento incoherente, pero intento tomar más conciencia de mi impacto.`,
  'Mi relación con los idiomas': `Ejemplo: Los idiomas me atraen porque cada lengua abre una forma distinta de pensar. Aprender palabras nuevas me hace sentir que también puedo habitar otras culturas y versiones de mí.`,
  'Mi relación con la programación': `Ejemplo: La programación me gusta porque convierte ideas en herramientas. Me frustra cuando algo falla, pero también me emociona esa sensación de construir lógica que otra persona puede usar.`,
  'Mi relación con la inteligencia artificial': `Ejemplo: La inteligencia artificial me provoca fascinación y cautela. Veo posibilidades enormes para crear y aprender, pero también me pregunto qué partes humanas no deberíamos delegar sin pensar.`,
  'Mi relación con las inversiones': `Ejemplo: Las inversiones me interesan porque obligan a pensar en paciencia, riesgo y futuro. Estoy aprendiendo a no confundir ambición con apuestas impulsivas ni seguridad con miedo a crecer.`,
  'Mi mejor consejo': `Ejemplo: Mi mejor consejo sería no negociar tu paz para sostener una imagen. Lo aprendí tarde, después de intentar agradar, demostrar y permanecer en lugares donde ya no me reconocía.`,
  'Mi prototipo físico de pareja': `Ejemplo: Mi prototipo físico de pareja incluye rasgos que me atraen, pero no se reduce a medidas. Me importa una presencia, una forma de moverse y una energía que despierte deseo y calma.`,
  'Mi prototipo de personalidad de pareja': `Ejemplo: Mi prototipo de personalidad de pareja es alguien claro, curioso y afectivamente responsable. Me atrae la gente que sabe conversar, pedir perdón, sostener deseo y no convertir todo en competencia.`,
  'Mi comida': `Ejemplo: Mi comida favorita me conecta con recuerdos específicos. No es solo sabor; es una mesa, una persona, una etapa de mi vida y una sensación de hogar que aparece al probarla.`,
  'Mi música': `Ejemplo: Mi música dice mucho de mis estados internos. Hay canciones para mi tristeza, para mi ego, para mi deseo y para esos momentos en que necesito sentirme acompañado sin hablar.`,
  'Mi película': `Ejemplo: Mi película favorita me marcó porque vi algo mío en un personaje o una escena. Cada vez que la recuerdo, entiendo mejor un miedo, una esperanza o una forma de mirar la vida.`,
  'Mi serie': `Ejemplo: Mi serie favorita me atrapó porque sus personajes crecían, fallaban y se contradecían como personas reales. Creo que me gustó porque acompañó una etapa concreta de mi vida.`,
  'Mi libro': `Ejemplo: Mi libro favorito me encontró en un momento donde necesitaba palabras para algo que no sabía explicar. Lo recuerdo por una idea que me cambió la forma de entenderme.`,
  'Mi color': `Ejemplo: Mi color favorito tiene una emoción asociada. Lo elijo porque me transmite calma, fuerza, misterio o alegría, y de alguna manera siento que representa una parte de mi temperamento.`,
  'Mi estilo': `Ejemplo: Mi estilo muestra cómo quiero presentarme sin tener que explicarlo todo. A veces busco comodidad, otras impacto, y otras simplemente vestir una versión de mí que necesito sentir cerca.`,
  'Mi hogar': `Ejemplo: Mi hogar no es solo un lugar; es una sensación de seguridad. Lo imagino con ciertos olores, silencios, personas y rutinas que me permitan bajar la guardia.`,
  'Mi ciudad': `Ejemplo: Mi ciudad me formó con su ritmo, sus oportunidades y sus límites. Hay partes que amo, partes que critico y recuerdos que solo tienen sentido porque ocurrieron en esas calles.`,
  'Mi casa': `Ejemplo: Mi casa ideal tendría espacios donde pudiera descansar, crear y compartir sin sentir invasión. Más que lujo, quiero una casa que refleje calma, identidad y cierta libertad cotidiana.`,
  'Mi habitación': `Ejemplo: Mi habitación revela mi intimidad: lo que dejo a la vista, lo que escondo y cómo descanso. Es el lugar donde más se nota mi orden, mi caos y mi necesidad de refugio.`,
  'Mi mascota': `Ejemplo: Mi mascota me enseñó una forma de amor simple y constante. Hablaría de sus gestos, de cómo cambió mis días y de lo que me mostró sobre cuidado y compañía.`,
  'Mi proyecto': `Ejemplo: Mi proyecto representa una apuesta por algo que todavía no existe del todo. Me emociona porque mezcla esfuerzo, miedo y visión, y porque siento que ahí pongo una parte auténtica de mí.`,
  'Mi comunidad': `Ejemplo: Mi comunidad es el grupo donde siento pertenencia o deseo sentirla. Contaría qué compartimos, qué me aporta y qué responsabilidades aparecen cuando uno deja de pensar solo en sí mismo.`,
  'Mi invento': `Ejemplo: Mi invento sería una solución para algo que me ha molestado o dolido durante años. Lo imaginaría útil, humano y nacido de una necesidad que conozco de cerca.`,
  'Mi Dios': `Ejemplo: Mi Dios, si intento nombrarlo, no cabe del todo en una doctrina. Lo relaciono con presencia, misterio, justicia o consuelo, y también con preguntas que todavía no sé responder.`,
  'Mi Diablo': `Ejemplo: Mi Diablo representa aquello que me tienta, me divide o me empuja a traicionarme. No lo veo solo como mal externo, sino como una parte oscura que debo reconocer.`,
  'Mi bien': `Ejemplo: Mi bien está en las decisiones que me acercan a la paz y al cuidado. Para mí hacer el bien no siempre es agradar, a veces es decir una verdad incómoda.`,
  'Mi mal': `Ejemplo: Mi mal aparece cuando actúo desde resentimiento, ego o miedo. No me gusta admitirlo, pero sé que tengo sombras capaces de herir si no las miro con honestidad.`,
  'Mi creencia': `Ejemplo: Mi creencia más fuerte es que una persona puede cambiar si se mira sin mentirse. Esa idea me sostiene porque he visto cómo una decisión honesta puede romper patrones viejos.`,
  'Mi religión': `Ejemplo: Mi religión, o mi distancia con ella, está marcada por experiencias familiares, dudas y momentos de búsqueda. Hablaría de lo que conservo, lo que rechazo y lo que todavía me conmueve.`,
  'Mi política': `Ejemplo: Mi política nace de lo que considero justo y de lo que he visto faltar. No quiero repetir consignas; prefiero explicar qué experiencias formaron mi postura y qué contradicciones reconozco.`,
  'Mi ángel': `Ejemplo: Mi ángel sería esa parte de mí que intenta cuidar, perdonar y seguir creyendo. Aparece cuando alguien necesita ayuda o cuando decido no responder desde mi peor impulso.`,
  'Mi demonio': `Ejemplo: Mi demonio es la voz que exagera mi orgullo, mi deseo de control o mi rabia. No siempre gana, pero conocerlo me ayuda a no fingir que soy puro.`,
  'Mi pecado': `Ejemplo: Mi pecado tiene que ver con una tendencia que repito aunque sepa que me hace daño. Puede ser soberbia, deseo, evasión o silencio, y quiero entender qué busca proteger.`,
  'Mis ídolos': `Ejemplo: Mis ídolos muestran lo que admiro y lo que quisiera desarrollar en mí. No los veo perfectos; me interesan por su talento, valentía, disciplina o forma de sostener una visión.`,
}

const getWritingExample = (prompt) =>
  writingExamples[prompt] ??
  `Ejemplo: Escribiría una experiencia concreta relacionada con ${prompt.toLocaleLowerCase('es-CO')}, explicando qué pasó, cómo me marcó y qué revela de mí hoy.`

const createQuestion = (prompt, index) => ({
  id: index + 1,
  key: `Revelación:${prompt}`,
  category: 'Revelación',
  prompt,
  suggestedPrice: '0.10',
  writingExample: getWritingExample(prompt),
  minWords: 100,
  maxWords: 2000,
  maxCharacters: 12000,
  fields,
})

export const questions = prompts.map(createQuestion)

export const getQuestion = (id) =>
  questions.find((question) => question.id === Number(id))
