const prompts = [
  'Mi autobiografía',
  'Yo en 3 años',
  'Yo en 5 años',
  'Yo en 10 años',
  'Mis fantasias sociales',
  'Mis fantasias espirituales',
  'Mis fantasias profesionales',
  'Mis fantasias economicas',
  'Mis fantasias romanticas',
  'Mis fantasias sexuales',
  'Mis fetiches',
  'Mi infancia',
  'Mi adolescencia',
  'Mi adultez',
  'Mi primera cita',
  'Mi última cita',
  'Mi mejor cita',
  'Mi peor cita',
  'Mi peor error',
  'Mi acierto',
  'Mi fracaso',
  'Mi logro',
  'Mi arrepentimiento',
  'Mis viajes',
  'Mis empleos',
  'Mis aventuras',
  'Mis fiestas',
  'Mis pérdidas',
  'Mis desafíos',
  'Mis mudanzas',
  'Mis miedos',
  'Mis deseos',
  'Mis principios económicos',
  'Mis principios sexuales',
  'Mis principios sociales',
  'Mis principios emocionales',
  'Mis límites económicos',
  'Mis límites sexuales',
  'Mis límites sociales',
  'Mis límites emocionales',
  'Mi decisión más difícil',
  'Mi decisión de la que más orgulloso estoy',
  'Mi renuncia',
  'Mi sacrificio',
  'Mi mayor cambio',
  'Mi punto de quiebre',
  'Mi pareja',
  'Mis parejas',
  'Mis exparejas',
  'Mi expareja que más extraño',
  'Mi amante',
  'Mi enemigo',
  'Mi rival',
  'Mi crush',
  'Mi admirador',
  'Mi amor imposible',
  'Mi confidente',
  'Mi cómplice',
  'Mi persona favorita',
  'Mi terapeuta',
  'Mi mamá',
  'Mi papá',
  'Mis hijos',
  'Mis hijas',
  'Mis hermanos',
  'Mis hermanas',
  'Mis abuelos',
  'Mis abuelas',
  'Mis tíos',
  'Mis tías',
  'Mis primos',
  'Mis primas',
  'Mi suegro',
  'Mi suegra',
  'Mis cuñados',
  'Mis cuñadas',
  'Mi mejor amigo',
  'Mi mejor amiga',
  'Mis amigos',
  'Mis amigas',
  'Mis vecinos',
  'Mis vecinas',
  'Mi jefe',
  'Mi líder',
  'Mis socios',
  'Mis socias',
  'Mis empleados',
  'Mis empleadas',
  'Mis clientes',
  'Mis clientas',
  'Mis compañeros de trabajo',
  'Mis compañeras de trabajo',
  'Mis profesores',
  'Mis profesoras',
  'Mis alumnos',
  'Mis alumnas',
  'Mis mentores',
  'Mis mentoras',
  'Mi sexualidad',
  'Mi dinero',
  'Mi fidelidad',
  'Mi familia',
  'Mi trabajo',
  'Mi salud',
  'Mi cuerpo',
  'Mi mente',
  'Mi rutina',
  'Mi deporte',
  'Mi arte',
  'Mi talento',
  'Mi vicio',
  'Mi debilidad',
  'Mi fortaleza',
  'Mi yo deseado',
  'Mi cuerpo deseado',
  'Mi mente deseada',
  'Mi vida deseada',
  'Mi propósito',
  'Mi proyecto de vida',
  'Mi futuro',
  'Mi legado',
  'Mi relación con la ciencia',
  'Mi relación con la historia',
  'Mi relación con la educación',
  'Mi relación con la medicina',
  'Mi relación con la tecnología',
  'Mi relación con la economía',
  'Mi relación con la política',
  'Mi relación con la religión',
  'Mi relación con la geografía',
  'Mi relación con la filosofía',
  'Mi relación con la psicología',
  'Mi relación con el derecho',
  'Mi relación con las finanzas',
  'Mi relación con el emprendimiento',
  'Mi relación con el liderazgo',
  'Mi relación con la comunicación',
  'Mi relación con el arte',
  'Mi relación con la música',
  'Mi relación con el deporte',
  'Mi relación con la gastronomía',
  'Mi relación con la agricultura',
  'Mi relación con el medio ambiente',
  'Mi relación con los idiomas',
  'Mi relación con la programación',
  'Mi relación con la inteligencia artificial',
  'Mi relación con las inversiones',
  'Mi mejor consejo',
  'Mi prototipo físico de pareja',
  'Mi prototipo de personalidad de pareja',
  'Mi comida',
  'Mi música',
  'Mi película',
  'Mi serie',
  'Mi libro',
  'Mi color',
  'Mi estilo',
  'Mi hogar',
  'Mi ciudad',
  'Mi casa',
  'Mi habitación',
  'Mi mascota',
  'Mi proyecto',
  'Mi comunidad',
  'Mi invento',
  'Mi Dios',
  'Mi Diablo',
  'Mi bien',
  'Mi mal',
  'Mi creencia',
  'Mi religión',
  'Mi política',
  'Mi ángel',
  'Mi demonio',
  'Mi pecado',
  'Mis ídolos',
]

const fields = [
  {
    key: 'revelation',
    label: 'Redacción personal',
    type: 'textarea',
    placeholder: 'Escribe tu revelación personal sobre esta tarjeta',
  },
]

const writingExamples = {
  'Mi autobiografía': `Ejemplo: Mi nombre es Andrés Martínez. Nací en Medellín el 14 de mayo de 1994. Viví allí hasta 2008, luego me mudé con mi familia a Bogotá, donde terminé el colegio y empecé a trabajar. En 2016 cambié de ciudad otra vez, esta vez por decisión propia, y desde entonces mi vida ha estado marcada por independencia, aprendizaje y varios comienzos difíciles.`,
  'Yo en 3 años': `Ejemplo: En tres años quiero tener ahorrados 40 millones de pesos, no deber tarjetas de crédito, haber comprado una moto o dar la cuota inicial de un apartamento pequeño. También me gustaría estar trabajando como coordinador comercial o tener activo un negocio de ropa y tenis que venda al menos 8 millones mensuales.`,
  'Yo en 5 años': `Ejemplo: En cinco años deseo vivir en una casa propia o estar pagando un apartamento de dos habitaciones. Me gustaría estar casado o en una relación estable, tener un fondo de emergencia de 12 meses y ganar mínimo 12 millones mensuales entre empleo, negocio e inversiones.`,
  'Yo en 10 años': `Ejemplo: En diez años quiero tener una familia formada, una casa terminada de pagar o muy avanzada, un vehículo propio y un negocio que no dependa solo de mi presencia diaria. También quisiera viajar una vez al año y haber ayudado a mis padres con algo concreto, como salud o vivienda.`,
  'Mis fantasias sociales': `Ejemplo: Fantaseo con llegar a una cena en un restaurante de Bogotá donde haya empresarios, artistas y amigos, y sentir que todos me reconocen por algo que construí. Me gustaría hablar sin timidez, vestir bien, hacer reír a la mesa y salir con tres invitaciones nuevas para proyectos reales.`,
  'Mis fantasias espirituales': `Ejemplo: Fantaseo con pasar una semana en una finca sin celular, despertarme a las 5:30 a.m., meditar, escribir y sentir que por fin entiendo qué debo soltar. Me gustaría tener una señal clara, como perdonar a alguien o dejar una culpa que llevo años cargando.`,
  'Mis fantasias profesionales': `Ejemplo: Imagino entrar a una oficina propia con mi nombre en la puerta, dirigir un equipo de 12 personas y presentar un proyecto frente a una empresa grande como Bancolombia, Rappi o Mercado Libre. Quiero que mis ideas se paguen bien y que mi criterio sea buscado, no tolerado.`,
  'Mis fantasias economicas': `Ejemplo: Fantaseo con revisar mi cuenta y ver 150 millones ahorrados, cero deudas malas y dos ingresos mensuales: mi trabajo principal y un local de ropa urbana que venda tenis importados. Me gustaría pagar un viaje familiar sin pedir cuotas ni sentir ansiedad.`,
  'Mis fantasias romanticas': `Ejemplo: Fantaseo con vivir con alguien en un apartamento luminoso, desayunar juntos los domingos, planear un viaje a Cartagena y saber que esa persona me escribe no por obligación sino porque me extraña. Quiero una relación donde hablemos de matrimonio sin miedo ni presión.`,
  'Mis fantasias sexuales': `Ejemplo: Fantaseo con una noche planeada con confianza: hotel bonito, conversación previa, límites claros y deseo mutuo sin pena. Me atrae poder decir lo que me gusta, escuchar lo que la otra persona quiere y sentir que la intimidad no es actuación sino complicidad.`,
  'Mis fetiches': `Ejemplo: Me atraen detalles muy específicos, como unas botas negras, una voz segura o una persona que tome la iniciativa sin ser brusca. No se trata solo del objeto o gesto, sino de la actitud que despierta en mí: curiosidad, tensión y ganas de dejarme llevar.`,
  'Mi infancia': `Ejemplo: Crecí en una casa pequeña del barrio San Javier. Recuerdo jugar fútbol en la calle hasta las 6 de la tarde, esconder mis cuadernos cuando sacaba mala nota y esperar a mi mamá cuando volvía del trabajo. Entre 2001 y 2006 aprendí a ser obediente, pero también a guardar muchas cosas.`,
  'Mi adolescencia': `Ejemplo: En mi adolescencia, entre los 13 y los 17 años, pasaba mucho tiempo intentando encajar. En el colegio me daba pena hablarle a quien me gustaba, me comparaba con mis compañeros y empecé a usar ropa ancha para ocultar inseguridades. También descubrí la música que todavía me acompaña.`,
  'Mi adultez': `Ejemplo: Mi adultez empezó de verdad cuando a los 22 años tuve que pagar arriendo, mercado y transporte con un sueldo de 1.200.000 pesos. Ahí entendí que quejarme no resolvía nada y que cada decisión, desde una deuda hasta una relación, tenía consecuencias concretas.`,
  'Mi primera cita': `Ejemplo: Mi primera cita fue en un centro comercial, tomando helado porque no tenía dinero para más. Llegué 20 minutos antes, ensayé temas de conversación y me puse una camisa azul que me quedaba grande. Me dio pena darle la mano, pero recuerdo que volví a casa sonriendo.`,
  'Mi última cita': `Ejemplo: Mi última cita fue un viernes por la noche en un café de Chapinero. Hablamos de trabajo, familia y relaciones pasadas. Me gustó su forma de escuchar, pero noté que evitaba responder cuando pregunté qué buscaba realmente, y eso me dejó pensando.`,
  'Mi mejor cita': `Ejemplo: Mi mejor cita fue una tarde de lluvia caminando por el centro. Entramos a una librería, compramos café barato y terminamos hablando tres horas sobre infancia, miedos y planes. No hubo lujo, pero sentí que no tenía que fingir nada.`,
  'Mi peor cita': `Ejemplo: Mi peor cita fue con alguien que pasó casi toda la cena mirando el celular y hablando de su ex. Yo había reservado mesa y me esforcé por conversar, pero a los 40 minutos ya quería irme. Me enseñó a no ignorar la incomodidad por educación.`,
  'Mi peor error': `Ejemplo: Mi peor error fue firmar como codeudor de un amigo en 2019 por 7 millones de pesos. Confié sin leer bien, él dejó de pagar y terminé asumiendo una deuda que dañó mi historial y nuestra amistad. Aprendí que querer ayudar no significa poner mi estabilidad en riesgo.`,
  'Mi acierto': `Ejemplo: Mi mayor acierto fue renunciar a un trabajo donde ganaba 2.300.000 pesos pero vivía agotado, para aceptar uno de menor salario mientras estudiaba análisis de datos. Seis meses después conseguí un cargo mejor y entendí que retroceder un paso también puede ser estrategia.`,
  'Mi fracaso': `Ejemplo: Mi fracaso más claro fue abrir una tienda virtual de camisetas en 2021 sin estudiar costos, envíos ni publicidad. Invertí 3 millones, vendí poco y quedé con inventario guardado. Me dolió, pero aprendí que una idea bonita no reemplaza un plan serio.`,
  'Mi logro': `Ejemplo: Mi logro fue terminar la universidad trabajando de día y estudiando de noche. Hubo semestres en los que dormía cuatro horas, debía mensualidades y pensé en aplazar. Cuando recibí el diploma, sentí que no era solo un papel: era prueba de resistencia.`,
  'Mi arrepentimiento': `Ejemplo: Me arrepiento de no haber visitado más a mi abuelo en 2020, cuando todavía podía conversar. Siempre decía que iría el domingo siguiente, hasta que se enfermó. Hoy me pesa haber tratado el tiempo con él como si fuera infinito.`,
  'Mis viajes': `Ejemplo: Mi viaje a Santa Marta en 2022 me mostró una versión más libre de mí. Fui con dos amigos, dormimos en un hostal barato, subimos al Tayrona y una noche terminé hablando con desconocidos sobre cambiar de vida. Volví con ganas de moverme más.`,
  'Mis empleos': `Ejemplo: Mi primer empleo fue empacando pedidos en una bodega por turnos de 10 horas. Después trabajé en call center, ventas y soporte. Cada empleo me dejó una marca: aprendí puntualidad, paciencia con clientes difíciles y la certeza de que no quiero depender toda la vida de un jefe.`,
  'Mis aventuras': `Ejemplo: Una aventura fue irme un fin de semana a Salento con 180.000 pesos, una maleta pequeña y dos personas que casi no conocía. Dormimos apretados, caminamos hasta el Valle del Cocora y terminé descubriendo que a veces necesito menos control para sentirme vivo.`,
  'Mis fiestas': `Ejemplo: Recuerdo una fiesta de diciembre en 2018 donde bailé hasta las 4 a.m., besé a alguien que me gustaba y al día siguiente desperté con culpa porque había prometido no volver a mezclar alcohol con despecho. Esa noche resume mi lado impulsivo.`,
  'Mis pérdidas': `Ejemplo: Una de mis pérdidas fue vender la bicicleta que usaba para ir al trabajo porque necesitaba pagar arriendo. No era solo un objeto: representaba independencia. Ese mes entendí lo humillante que puede sentirse perder algo pequeño cuando ya estás cansado.`,
  'Mis desafíos': `Ejemplo: Uno de mis desafíos fue vivir seis meses solo en una ciudad donde no conocía a nadie. Tenía que cocinar, trabajar, cuidar mis gastos y no llamar llorando cada noche. Aprendí a acompañarme, aunque muchos días me sentí abandonado.`,
  'Mis mudanzas': `Ejemplo: Me mudé de Medellín a Bogotá en 2008, luego a Soacha en 2014 y a Cali en 2021 por trabajo. Cada mudanza significó empacar libros, dejar amigos y aprender una nueva ruta de buses. No solo cambié de casa; cambié de versión.`,
  'Mis miedos': `Ejemplo: Me da miedo llegar a los 40 años sin casa, sin pareja estable y con deudas que me obliguen a aceptar cualquier trabajo. También me asusta enfermarme y no tener ahorros para responder. Por eso a veces soy demasiado controlador con el dinero.`,
  'Mis deseos': `Ejemplo: Deseo comprar un apartamento antes de los 35, tener una pareja con quien pueda hablar de hijos sin pánico, viajar a México y montar un negocio de ropa deportiva. También deseo algo menos visible: dormir tranquilo sin sentir que voy tarde en la vida.`,
  'Mis principios económicos': `Ejemplo: Mi principio económico principal es no endeudarme para aparentar. Prefiero usar un celular de hace tres años antes que pagar 24 cuotas por impresionar. También creo que si gano más, primero debo ahorrar, ayudar en casa y luego darme gustos.`,
  'Mis principios sexuales': `Ejemplo: Para mí no hay deseo sin consentimiento claro. No me gusta insistir si alguien duda, y prefiero hablar antes de asumir. También creo que cuidarse con preservativo y decir la verdad sobre otras relaciones es parte del respeto, no un detalle opcional.`,
  'Mis principios sociales': `Ejemplo: En lo social intento no burlarme de quien está ausente para quedar bien con el grupo. Si invito a alguien, lo incluyo; si prometo ir, aviso si no puedo. Me importan esos gestos pequeños porque muestran carácter.`,
  'Mis principios emocionales': `Ejemplo: Mi principio emocional es no castigar con silencio. Si estoy molesto, puedo pedir unas horas, pero no desaparecer tres días para manipular. También intento no decir “no pasa nada” cuando sí pasa, porque luego eso se vuelve resentimiento.`,
  'Mis límites económicos': `Ejemplo: No presto dinero que necesito para arriendo, salud o comida. Puedo ayudar con 50.000 o 100.000 pesos si puedo perderlos sin rabia, pero no vuelvo a sacar créditos para nadie ni a pagar cuentas de una pareja por miedo a que se vaya.`,
  'Mis límites sexuales': `Ejemplo: No acepto tener intimidad sin preservativo con alguien que no conozco bien, ni hacer cosas que me incomodan solo para parecer abierto. También necesito poder parar en cualquier momento sin que la otra persona se enoje o me presione.`,
  'Mis límites sociales': `Ejemplo: No me quedo en grupos donde la diversión depende de humillar a alguien. Tampoco acepto que me graben borracho, que revisen mi celular como chiste o que me obliguen a gastar dinero para no verme tacaño.`,
  'Mis límites emocionales': `Ejemplo: Mi límite emocional es no perseguir a alguien que responde cuando quiere, cancela planes sin explicación y luego vuelve como si nada. Puedo querer mucho, pero no quiero volver a vivir pendiente de una notificación para sentirme valioso.`,
  'Mi decisión más difícil': `Ejemplo: Mi decisión más difícil fue terminar una relación de cuatro años aunque ya habíamos hablado de vivir juntos. La quería, pero peleábamos cada semana, yo lloraba en silencio y entendí que casarnos habría sido convertir el miedo a quedarme solo en un contrato.`,
  'Mi decisión de la que más orgulloso estoy': `Ejemplo: La decisión de la que más orgulloso estoy fue pagar mis deudas una por una durante 18 meses. Dejé de salir, vendí mi consola y anoté cada pago en una libreta. El día que quedé en cero sentí más libertad que cuando compraba cosas.`,
  'Mi renuncia': `Ejemplo: Renuncié a un puesto en 2022 después de que mi jefe me gritara frente al equipo por tercera vez. Tenía miedo porque no había ahorrado mucho, pero preferí buscar otro empleo antes que acostumbrarme a ser tratado como si no valiera.`,
  'Mi sacrificio': `Ejemplo: Mi sacrificio fue dejar de estudiar un semestre para ayudar con los gastos de mi casa cuando mi mamá perdió el empleo. Trabajé turnos extra, pagué servicios y me atrasé en mi carrera. No me arrepiento, pero sí me dolió pausar mi propio plan.`,
  'Mi mayor cambio': `Ejemplo: Mi mayor cambio fue dejar de tomar todos los fines de semana después de una pelea familiar en 2021. Borré contactos de rumba, empecé a entrenar a las 6 a.m. y descubrí que mucha gente solo estaba cerca cuando había fiesta.`,
  'Mi punto de quiebre': `Ejemplo: Mi punto de quiebre fue una noche en la que revisé mi cuenta y tenía 18.000 pesos, tres deudas vencidas y cero ganas de levantarme al día siguiente. Ese día escribí una lista de cosas que debía cambiar porque ya no podía seguir improvisando.`,
  'Mi pareja': `Ejemplo: Mi pareja es Juliana Ramírez. Vivimos juntos desde hace dos años y ocho meses en un apartamento pequeño en Laureles. Estoy con ella porque me produce seguridad: no seguridad de rutina, sino de poder llegar cansado y sentir que no tengo que actuar. Hemos viajado a Santa Marta, compramos una moto entre los dos y aprendimos a dividir gastos sin convertir cada peso en una pelea. Me gusta que me aterriza cuando me acelero, pero también me incomoda que a veces siento que depende demasiado de mí para decidir.`,
  'Mis parejas': `Ejemplo: Mis parejas actuales son Laura y Andrés. Con Laura llevo tres años, compartimos casa y una cuenta para los gastos comunes; con Andrés llevo nueve meses y nos vemos tres veces por semana. Los tres sabemos de la relación y tenemos acuerdos claros sobre tiempo, salud sexual, celos y decisiones importantes. Esta tarjeta existe porque mi vida afectiva no cabe en la palabra “pareja” en singular. No es una fantasía ni una excusa para evitar compromiso: es una forma de amar que me exige más comunicación, más honestidad y más responsabilidad.`,
  'Mis exparejas': `Ejemplo: Mis exparejas más importantes fueron Camila, Mateo y Daniela. Con Camila aprendí lo que era vivir pendiente de una aprobación; con Mateo entendí que la química no alcanza cuando no hay proyecto; con Daniela tuve una relación tranquila, pero yo estaba demasiado inmaduro para cuidarla. No las pongo en la misma bolsa: cada historia tuvo errores concretos, viajes, discusiones, cumpleaños y despedidas distintas. Si hoy amo mejor es porque esas relaciones me mostraron exactamente dónde mentía, dónde huía y dónde confundía intensidad con amor.`,
  'Mi expareja que más extraño': `Ejemplo: La expareja que más extraño es Daniela. Terminamos en 2021 después de casi cuatro años, y todavía recuerdo los desayunos de domingo, las caminatas por Envigado y la forma en que se reía cuando yo inventaba planes absurdos. No extraño nuestras peleas ni mi manera de cerrarme cuando ella quería hablar; extraño la sensación de hogar que tuvimos durante un tiempo. A veces me pregunto si la extraño a ella o a la versión de mí que todavía creía que todo se podía arreglar con amor y paciencia.`,
  'Mi amante': `Ejemplo: Mi amante es Valeria, una mujer que conocí en un congreso en Cali y con quien mantengo una relación que no cabe del todo en las categorías limpias. Nos vemos algunas noches, hablamos por mensajes cuando podemos y hemos tenido que poner acuerdos para no convertir el deseo en daño. Con ella siento intensidad, validación y una libertad que me obliga a mirarme con honestidad. También siento culpa, límites y preguntas incómodas. No la nombro para presumirla; la nombro porque su presencia actual revela cómo manejo deseo, secreto, responsabilidad y verdad.`,
  'Mi enemigo': `Ejemplo: Mi enemigo es Óscar, un excompañero de trabajo que todavía desacredita mis ideas cada vez que coincidimos en un proyecto. No es una enemistad de gritos, sino de correos copiados a todos, comentarios sarcásticos y pequeñas jugadas para hacerme quedar mal. Me cuesta aceptar cuánto me activa. Cuando trato con él puedo volverme calculador, orgulloso y demasiado pendiente de ganar. Óscar me muestra una parte mía que necesita defenderse, pero también una parte que debe aprender a elegir paz sin sentirse derrotada.`,
  'Mi rival': `Ejemplo: Mi rival es Santiago. Trabajamos en el mismo sector, competimos por clientes parecidos y cada logro suyo me obliga a revisar mi propia ambición. Me molesta admitirlo, pero cuando publica un proyecto grande siento una mezcla de respeto, envidia y urgencia. Él me empuja a estudiar más, presentar mejor mis ideas y no dormirme en lo que ya sé hacer. También me muestra cuánto de mi impulso nace del miedo a quedarme atrás. Mi rivalidad con Santiago me exige crecer sin perderme comparándome.`,
  'Mi crush': `Ejemplo: Mi crush es Mariana, la barista del café donde trabajo algunos viernes. Sé poco de ella: que estudia diseño, que tiene un tatuaje de una luna en el brazo y que recuerda mi pedido sin preguntarme. Me gusta su forma de hablar calmada y el modo en que mira directo, pero soy consciente de que he inventado más de lo que conozco. Tal vez me atrae ella, o tal vez me atrae la idea de alguien que parece vivir con una ligereza que yo no tengo.`,
  'Mi admirador': `Ejemplo: Mi admirador es Nicolás, un amigo de mi hermana que reacciona a casi todo lo que publico, me invita a planes y me dice sin rodeos que le gusta mi manera de pensar. Me halaga porque vengo de una etapa en la que me sentí poco deseado, pero también me incomoda porque yo no siento lo mismo. A veces respondo por culpa y eso puede alimentar una expectativa que no quiero sostener. Nicolás me está enseñando que recibir cariño también exige responsabilidad y límites claros.`,
  'Mi amor imposible': `Ejemplo: Mi amor imposible es Carolina. Trabaja conmigo, tiene pareja y jamás ha cruzado ningún límite, pero yo he construido demasiadas escenas internas alrededor de sus mensajes, sus bromas y la forma en que escucha mis ideas. Sé que no es una posibilidad real, y aun así hay días en que espero coincidir con ella como si eso cambiara algo. Carolina me muestra una parte mía que idealiza la distancia porque ahí no tiene que arriesgarse a una relación concreta, con problemas concretos.`,
  'Mi confidente': `Ejemplo: Mi confidente es Felipe. Nos conocemos desde 2016 y él sabe cosas que no le he contado ni a mi familia: mis deudas, mis dudas sobre ser papá, la vez que pensé en renunciar sin tener plan y mis miedos en la relación. No me aconseja para sentirse superior; primero escucha, pregunta y solo después opina. Con Felipe aprendo que la confianza no aparece por hablar mucho, sino por comprobar durante años que alguien no usa tu vulnerabilidad como chisme ni como arma.`,
  'Mi cómplice': `Ejemplo: Mi cómplice es Lina. Con ella monté mi primer negocio informal vendiendo chaquetas por Instagram, inventé excusas para escaparnos a conciertos y también tomé decisiones arriesgadas que no siempre salieron bien. Lina entiende mi lado impulsivo y creativo sin pedirme que lo vuelva presentable. A veces esa complicidad me ha impulsado; otras, nos ha llevado a justificar cosas que debimos pensar mejor. Ella representa esa parte de mí que necesita aventura, pero también límites para no confundir lealtad con irresponsabilidad.`,
  'Mi persona favorita': `Ejemplo: Mi persona favorita es mi abuela Teresa. Tiene 78 años, vive en Manizales y todavía me llama los martes para preguntarme si estoy comiendo bien. No es perfecta: puede ser terca, intensa y opinar de más, pero con ella siento una ternura que no siento con nadie. Cuando voy a verla, me prepara arepas y me cuenta las mismas historias de mi abuelo. Su presencia me baja la velocidad. Me recuerda que antes de querer demostrar algo, fui un niño cuidado por alguien.`,
  'Mi terapeuta': `Ejemplo: Mi terapeuta se llama Adriana. La veo desde 2023, después de una ruptura y de varios meses durmiendo mal. Al principio iba con discursos muy ordenados para no sentirme vulnerable; ahora ella me detiene y me pregunta qué estoy sintiendo en el cuerpo. Con Adriana estoy entendiendo mi miedo al abandono, mi costumbre de complacer y la rabia que escondo detrás de ser “tranquilo”. No me salva la vida mágicamente, pero me da un espacio donde puedo dejar de mentirme con tanta elegancia.`,
  'Mi mamá': `Ejemplo: Mi mamá es Patricia. Trabajó muchos años como auxiliar de enfermería y casi siempre llegaba cansada, pero aun así revisaba mis tareas y me dejaba comida servida. Le agradezco su resistencia y la forma en que sostuvo la casa cuando mi papá estuvo ausente. También me duele que a veces usara el sacrificio para hacerme sentir culpable. Mi relación con ella mezcla amor, deuda, admiración y límites. Todavía estoy aprendiendo a quererla sin volverme responsable de toda su tristeza.`,
  'Mi papá': `Ejemplo: Mi papá es Hernando. Cuando era niño lo veía como alguien fuerte porque sabía arreglar motos, negociar y entrar a cualquier lugar con seguridad. Después entendí que también era distante, orgulloso y malo para pedir perdón. Me enseñó disciplina y amor por el trabajo, pero también me dejó la costumbre de callarme cuando algo duele. Hoy hablamos más de fútbol y cuentas que de emociones. Aun así, cada conversación con él toca una parte mía que todavía quiere ser reconocido por su padre.`,
  'Mis hijos': `Ejemplo: Mis hijos son Samuel y Tomás. Samuel tiene nueve años y pregunta todo; Tomás tiene cinco y se enoja cuando no logra armar sus bloques. Ser su papá me cambió la relación con el tiempo: ya no puedo vivir solo desde mis impulsos. Me da orgullo llevarlos al colegio, enseñarles a montar bicicleta y verlos dormir después de un día difícil. También me asusta repetir mi impaciencia con ellos. Tener hijos me obliga a revisar mi carácter todos los días, no solo mis intenciones.`,
  'Mis hijas': `Ejemplo: Mis hijas son Emma y Lucía. Emma tiene once años y ya discute con una claridad que me desarma; Lucía tiene siete y todavía me busca la mano cuando cruzamos la calle. Con ellas aprendo que cuidar no es controlar. Me preocupa el mundo que van a enfrentar, pero no quiero educarlas desde el miedo. Quiero que sepan poner límites, hablar de su cuerpo sin vergüenza y no confundir amor con aguantar. Ellas me vuelven más atento, más blando y más responsable.`,
  'Mis hermanos': `Ejemplo: Mis hermanos son Andrés y Miguel. Andrés es el responsable, el que presta plata y media peleas; Miguel es el rebelde, el que se fue de la casa a los 19 y volvió años después con historias duras. Yo quedo en la mitad, intentando no incomodar. Con ellos siento protección, competencia y distancia. Hay meses en que casi no hablamos, pero si pasa algo grave aparecemos. Mis hermanos me recuerdan que una familia puede estar unida y herida al mismo tiempo.`,
  'Mis hermanas': `Ejemplo: Mis hermanas son Natalia y Paola. Natalia me cuidó cuando éramos niños y todavía cree que puede decirme cómo vivir; Paola es menor y me busca cuando necesita consejo, aunque luego haga lo contrario. Con ellas he tenido complicidad, peleas por herencias pequeñas, secretos compartidos y silencios largos. Me han enseñado a escuchar a mujeres cercanas sin intentar resolverlo todo. También me han mostrado lo difícil que me resulta pedir ayuda dentro de mi propia familia sin sentir que pierdo autoridad.`,
  'Mis abuelos': `Ejemplo: Mis abuelos son Luis y Rafael en mi memoria familiar. A Luis lo recuerdo sentado en una mecedora arreglando radios viejos y diciéndome que uno no promete lo que no puede cumplir. Rafael es más seco en mis recuerdos; trabajó en el campo y hablaba poco, pero una vez caminó conmigo dos horas para llevarme a entrenar fútbol. De ellos heredé disciplina, terquedad y una forma silenciosa de demostrar cariño. También heredé la idea equivocada de que los hombres fuertes no cuentan lo que les duele.`,
  'Mis abuelas': `Ejemplo: Mis abuelas son Teresa y Amparo en mi idea de hogar. Teresa me enseñó a rezar aunque después yo dudara de muchas cosas; Amparo me enseñó a cocinar arroz con coco y a no llegar con las manos vacías a una casa. Las dos tienen formas distintas de seguir presentes en mí: una con palabras, la otra con comida y recuerdos de cuidado. Cuando pienso en ellas aparecen olores, regaños y consejos repetidos. Mis abuelas todavía ordenan parte de lo que entiendo por ternura.`,
  'Mis tíos': `Ejemplo: Mis tíos más presentes son Jairo y Wilson. Jairo todavía me llama para hablar de negocios y preguntarme cómo va el trabajo; Wilson aparece en diciembre con regalos grandes y promesas que no siempre cumple. De uno aprendo constancia, del otro aprendo a desconfiar de la gente que habla demasiado bonito. Mis tíos me muestran modelos masculinos distintos a mi papá: algunos protectores, otros irresponsables, otros simplemente humanos. Con ellos entiendo que la familia también se evalúa por hechos actuales.`,
  'Mis tías': `Ejemplo: Mis tías son Clara y Mónica. Clara defiende a todos en las reuniones familiares; Mónica es más crítica y puede destruirte con una frase si no mide su tono. De niña me cuidaron, me peinaron y me llevaron a citas médicas cuando mi mamá trabajaba. Hoy todavía me acompañan, pero también he tenido que ponerles límites cuando opinan sobre mi cuerpo o mi relación. Mis tías representan esa mezcla de cuidado y presión familiar que uno agradece, pero también necesita ordenar.`,
  'Mis primos': `Ejemplo: Mis primos son Diego, Julián y Esteban. Con ellos crecí jugando fútbol en la calle, robando mangos de una finca y aprendiendo a competir sin llorar, aunque a veces sí lloraba escondido. Hoy tomamos caminos distintos: uno es policía, otro vive en Chile y otro casi no aparece. Cuando nos vemos en Navidad vuelve una confianza rara, como si todavía tuviéramos diez años. Mis primos me conectan con una versión mía más libre, más brusca y menos vigilada.`,
  'Mis primas': `Ejemplo: Mis primas son Ana, Sofía y Marcela. Con Ana hablo de música y de amores secretos; Sofía me presta ropa cuando quiero cambiar de estilo; Marcela fue la primera persona de la familia que me dijo que ir a terapia no era exagerado. Con ellas hay juegos antiguos, peleas viejas y conversaciones de cocina mientras los adultos discuten en la sala. Mis primas me ayudan a sentir pertenencia sin tener que actuar tan fuerte.`,
  'Mi suegro': `Ejemplo: Mi suegro es Alberto. La primera vez que fui a su casa me preguntó en qué trabajaba antes de preguntarme si quería café, y sentí que estaba en una entrevista. Con el tiempo descubrí que no era arrogancia, sino miedo a que su hija sufriera. Hoy hablamos de motos, de arreglos de la casa y de fútbol. Aún me cuesta no sentirme evaluado por él, pero también reconozco que me ha abierto espacio: me prestó herramientas cuando nos mudamos y me enseñó a instalar la lavadora.`,
  'Mi suegra': `Ejemplo: Mi suegra es Gloria. Al principio me parecía demasiado intensa porque llamaba a Juliana tres veces al día y opinaba sobre nuestra casa. Tuvimos roces cuando quiso decidir dónde pasaríamos Navidad y yo me sentí invadido. Con el tiempo aprendí que su forma de cuidar viene de haber criado sola a dos hijas. Hoy la quiero, pero también marco límites: no tiene llaves del apartamento y las decisiones de pareja las hablamos primero entre nosotros. Gloria me ha enseñado a negociar familia sin declarar guerra.`,
  'Mis cuñados': `Ejemplo: Mis cuñados son Sebastián y Mario. Sebastián vive cerca y se volvió casi un amigo: vemos partidos, nos prestamos herramientas y a veces me cuenta cosas que no habla con su hermana. Mario, en cambio, es distante y hace comentarios pesados cuando toma. Con ellos entendí que entrar a una familia no significa caerle bien a todos ni tragarse todo por amor a la pareja. Mis cuñados me han obligado a practicar respeto, humor y límites en un terreno donde uno no siempre tiene control.`,
  'Mis cuñadas': `Ejemplo: Mis cuñadas son Valentina y Camila. Valentina me recibió desde el principio, me agregó al grupo familiar y fue quien me explicó qué temas evitar en la mesa. Camila tardó más en confiar; creo que pensaba que yo iba a lastimar a su hermana. Con el tiempo hemos construido una relación cordial, con cafés, favores y alguna discusión por plata prestada. Mis cuñadas me muestran que una pareja no llega sola: llega con lealtades, historias y personas que también necesitan sentirse cuidadas.`,
  'Mi mejor amigo': `Ejemplo: Mi mejor amigo es Juan Pablo. Nos conocemos desde séptimo grado, cuando me defendió en una pelea que yo mismo había provocado. Ha estado en mis mudanzas, en mi ruptura con Daniela y en el día que firmé mi primer contrato grande. Con él puedo hablar de plata, sexo, miedo y fracaso sin sentir que debo adornar la historia. También hemos tenido distancia cuando se casó y yo seguía en modo fiesta. Nuestra amistad ha sobrevivido porque los dos hemos aprendido a volver sin cobrar ausencia.`,
  'Mi mejor amiga': `Ejemplo: Mi mejor amiga es Carolina. La conocí en un trabajo donde ambos odiábamos las reuniones de los lunes. Ella sabe leerme cuando digo que estoy bien y no lo estoy. Me ha acompañado en hospitales, entrevistas y conversaciones incómodas con mi familia. Con Carolina no hay tensión romántica, y eso ha sido un descanso: puedo quererla profundamente sin tener que convertirlo en otra cosa. Su amistad me enseñó que la intimidad también puede ser limpia, estable y radicalmente honesta.`,
  'Mis amigos': `Ejemplo: Mis amigos más cercanos son Juan, Felipe y Esteban. Juan es el que arma planes, Felipe el que escucha y Esteban el que aparece tarde pero aparece. Con ellos he viajado a Guatapé, he pedido plata prestada, he celebrado ascensos y también he tenido discusiones por chistes que cruzaron límites. No todos mis amigos conocen todas mis partes, pero cada uno sostiene una zona de mi vida. Estoy aprendiendo a no llamar amistad a la costumbre ni lealtad a aguantar faltas de respeto.`,
  'Mis amigas': `Ejemplo: Mis amigas son Carolina, Lina y Marcela. Carolina me aterriza, Lina me empuja a arriesgar y Marcela me dice verdades que a veces me duelen. Con ellas he hablado de deseo, trabajo, familia y de mis torpezas afectivas sin que todo se vuelva competencia. También he tenido que revisar cómo recibo el cuidado de mujeres sin volverlo dependencia emocional. Mis amigas me han hecho más sensible, menos defensivo y más consciente de las formas pequeñas en que uno puede cuidar o descuidar a alguien.`,
  'Mis vecinos': `Ejemplo: Mis vecinos son don Álvaro, los gemelos del 302 y una familia venezolana que llegó el año pasado. Don Álvaro me presta el taladro y se queja del ruido; los gemelos ponen música hasta tarde; la familia del 201 me ayudó una noche que se inundó la cocina. Con ellos no tengo una amistad profunda, pero sí una convivencia real hecha de saludos, favores, molestias y acuerdos. Mis vecinos me recuerdan que mi libertad termina donde empieza el descanso de otra persona.`,
  'Mis vecinas': `Ejemplo: Mis vecinas más presentes son Marta y Yuli. Marta vive sola, riega mis plantas cuando viajo y sabe más de mi horario que mi mamá. Yuli tiene una niña pequeña y a veces me pide que le reciba paquetes porque trabaja todo el día. Con ellas he construido una confianza cotidiana: saludarnos, avisarnos si hay alguien raro en la portería, prestarnos sal o una escalera. Mis vecinas me muestran que comunidad no siempre es amistad intensa; a veces es simplemente estar atento.`,
  'Mi jefe': `Ejemplo: Mi jefe es Ricardo, director de la agencia donde trabajo. Es brillante para vender ideas, pero le cuesta reconocer el trabajo del equipo. Muchas veces promete fechas imposibles al cliente y después nos pide quedarnos hasta tarde como si fuera normal. Aprendo muchísimo de estrategia con él, pero también estoy aprendiendo lo que no quiero tolerar: gritos, urgencias inventadas y mensajes de domingo como si mi vida no existiera. Ricardo me muestra mi necesidad de aprobación y el riesgo de confundir exigencia con abuso.`,
  'Mi líder': `Ejemplo: Mi líder es Marcela, la coordinadora de mi equipo. Organiza sin gritar, pregunta quién está saturado y defiende nuestros tiempos frente a gerencia cuando el cliente pide imposibles. Una vez corrigió una presentación mía durante una hora, pero salí motivado en vez de humillado. Con ella entiendo que liderar también es crear condiciones para que otros piensen mejor. Marcela me da un modelo concreto de autoridad: firme, clara y humana. Por eso comparo a muchos jefes con esa vara.`,
  'Mis socios': `Ejemplo: Mis socios son Daniel y César en una tienda de accesorios para motos. Daniel es bueno vendiendo, César lleva las cuentas y yo manejo redes. Cuando todo va bien hablamos de expansión, proveedores y domicilios; cuando algo se retrasa aparecen tensiones por plata, tiempo y responsabilidades. Con ellos estoy aprendiendo que la confianza sirve, pero no reemplaza claridad, números y límites. Mis socios revelan cómo negocio, cómo cedo y qué tan rápido me incomodo cuando siento que alguien no está poniendo lo mismo.`,
  'Mis socias': `Ejemplo: Mis socias son Laura y Fernanda en un proyecto de ropa deportiva. Laura diseña, Fernanda negocia con talleres y yo consigo clientes. Vendemos bien, pero chocamos cuando toca decidir si reinvertir o repartir ganancias. Admiro la disciplina de Laura y la valentía de Fernanda, aunque a veces me siento desplazado cuando toman decisiones sin mí. Mis socias me muestran que colaborar con gente talentosa exige hablar temprano de expectativas, propiedad, dinero y reconocimiento.`,
  'Mis empleados': `Ejemplo: Mis empleados son Kevin y Mauricio en el local de repuestos. Kevin es puntual y aprende rápido; Mauricio vende muy bien, pero llega tarde y me obliga a repetir conversaciones incómodas. Dirigirlos me muestra que no basta con ser buena persona: hay que explicar, corregir, pagar a tiempo y no prometer estabilidad si el negocio no la tiene. También cometo errores, como evitar llamados de atención por miedo a caer mal. Mis empleados me enseñan que la autoridad sin claridad termina siendo injusta.`,
  'Mis empleadas': `Ejemplo: Mis empleadas son Paola y Jenny en la tienda de ropa. Paola atiende con una paciencia impresionante; Jenny organiza inventario mejor que yo. Al principio quiero ser un jefe “relajado”, pero eso puede volver confusos los horarios y cargarles problemas míos. Estoy aprendiendo a separar confianza de desorden: pagar horas extra, escuchar quejas y dar instrucciones concretas. Mis empleadas me hacen ver que liderar también implica cuidar el ambiente donde otras personas pasan gran parte de su vida.`,
  'Mis clientes': `Ejemplo: Mis clientes más presentes son don Manuel, que siempre pide rebaja aunque tenga plata, y Andrés, que me recomienda con media empresa cuando una entrega queda bien hecha. Con ellos aprendo paciencia, negociación y la importancia de cumplir fechas. También tengo clientes que quieren cambios infinitos sin pagar más, y ahí practico que ser amable no significa regalar mi trabajo. Mis clientes me enseñan que vender no es solo convencer; es sostener una promesa después de recibir el dinero.`,
  'Mis clientas': `Ejemplo: Mis clientas más importantes son Paula, una emprendedora que confía en mí para lanzar su marca, y Claudia, una señora exigente que devuelve todo hasta que quede perfecto. Paula me enseña el valor de acompañar un proceso con paciencia; Claudia me enseña a dejar acuerdos por escrito. Con ellas entiendo que atender bien no es decir sí a todo, sino escuchar, explicar límites y responder cuando algo falla. Mis clientas afinan mi manera de trabajar con detalle y respeto.`,
  'Mis compañeros de trabajo': `Ejemplo: Mis compañeros de trabajo son Diego, Ana y Julián. Diego me cubre cuando tengo una crisis familiar; Ana me enseña a presentar informes sin enredarme; Julián compite por todo y a veces vuelve pesado el ambiente. Con ellos paso almuerzos rápidos, cierres hasta tarde y chismes de pasillo que pueden unir o dañar. Mis compañeros me muestran que el trabajo no se vive solo con tareas: también se vive con alianzas, roces, cansancio compartido y pequeñas lealtades diarias.`,
  'Mis compañeras de trabajo': `Ejemplo: Mis compañeras de trabajo son Paola, Marcela y Sofía. Paola me ayuda cuando no entiendo el sistema; Marcela me confronta cuando interrumpo demasiado en reuniones; Sofía se ha vuelto amiga después de meses de trabajar juntos en silencio. Con ellas aprendo a colaborar sin imponer mi ritmo. También entiendo que el respeto profesional se nota en detalles concretos: dar crédito, escuchar ideas completas y no convertir la confianza en comentarios fuera de lugar.`,
  'Mis profesores': `Ejemplo: Mis profesores más importantes son el profesor Rueda y el profesor Salazar. Rueda todavía me exige leer mejor y me presta libros cuando no puedo comprarlos; Salazar es más duro y a veces sus correcciones me hacen dudar antes de hablar en público. Los dos me marcan de formas opuestas. Mis profesores me muestran que una autoridad puede abrir o cerrar una puerta con una frase, y que yo todavía cargo algunas de esas frases cuando intento aprender algo nuevo.`,
  'Mis profesoras': `Ejemplo: Mis profesoras son Beatriz, Ángela y la profe Marta. Beatriz me exige leer en voz alta aunque me dé pena; Ángela entiende cuando una situación familiar me desordena; Marta me dice que pienso bien, pero escribo con miedo. Ellas no son solo docentes: son presencias concretas en una etapa donde estoy formando mi confianza. Mis profesoras me enseñan disciplina, sensibilidad y la importancia de que alguien vea potencial antes de que uno lo vea.`,
  'Mis alumnos': `Ejemplo: Mis alumnos en el curso de Excel son Carlos, Mateo y un señor llamado Hernán que tiene 62 años. Carlos aprende rápido pero se frustra si no es perfecto; Mateo hace chistes para tapar que no entiende; Hernán anota cada paso en una libreta azul. Enseñarles me obliga a bajar la velocidad y explicar sin humillar. Mis alumnos me muestran que saber algo no me hace superior, y que la paciencia es una forma muy concreta de respeto.`,
  'Mis alumnas': `Ejemplo: Mis alumnas son Valentina, Sara y Luz Dary en un taller de emprendimiento. Valentina tiene una idea de postres, Sara quiere vender accesorios y Luz Dary sostiene su casa con un negocio pequeño. Sus preguntas me obligan a hablar menos bonito y más útil: costos, margen, proveedores, miedo a cobrar. Con ellas entiendo que enseñar no es lucirse, sino servir. Mis alumnas me recuerdan que detrás de cada ejercicio hay una vida intentando mejorar con herramientas reales.`,
  'Mis mentores': `Ejemplo: Mis mentores son Germán y Andrés. Germán me enseña a negociar sin pedir perdón por cobrar; Andrés corrige mis propuestas comerciales hasta que dejan de sonar improvisadas. Ninguno es suave todo el tiempo, pero ambos apuestan por mí cuando todavía no tengo resultados grandes. También aprendo a no idealizarlos: Germán es impaciente y Andrés puede ser vanidoso. Mis mentores me dan dirección, pero me toca separar sus enseñanzas de sus defectos.`,
  'Mis mentoras': `Ejemplo: Mis mentoras son Claudia y Marcela. Claudia me abre la puerta a clientes serios y me enseña a preparar reuniones con datos, no solo entusiasmo. Marcela me muestra cómo liderar sin endurecerse, incluso en ambientes donde muchos confunden autoridad con gritar. Las dos me corrigen con firmeza y me defienden cuando todavía no tengo nombre propio en el sector. Mis mentoras me ayudan a tomarme en serio, pero también a entender que crecer no significa volverse inaccesible.`,
  'Mi sexualidad': `Ejemplo: Mi sexualidad ha sido una mezcla de descubrimiento, pudor, deseo y preguntas. Escribiría cómo la vivo, qué me da confianza y qué cosas todavía estoy aprendiendo a nombrar sin vergüenza.`,
  'Mi dinero': `Ejemplo: Mi dinero revela mis miedos y mis prioridades. A veces lo cuido por ansiedad, otras lo gasto para sentir libertad, y todavía aprendo a usarlo sin que defina mi valor.`,
  'Mi fidelidad': `Ejemplo: Mi fidelidad no es solo no traicionar; es decidir cómo cuido un acuerdo cuando aparece la tentación, la distancia o el aburrimiento. Contaría qué entiendo por lealtad real.`,
  'Mi familia': `Ejemplo: Mi familia es una mezcla de amor, historia, heridas y costumbres. Hay cosas que agradezco y otras que intento no repetir, porque de ahí viene mucho de mi forma de vincularme.`,
  'Mi trabajo': `Ejemplo: Mi trabajo no solo paga cuentas; también afecta mi autoestima. Escribiría qué busco en lo profesional, qué me agota y qué tipo de esfuerzo me hace sentir orgulloso.`,
  'Mi salud': `Ejemplo: Mi salud me ha obligado a escuchar señales que antes ignoraba. Contaría cómo cuido o descuido mi cuerpo, qué miedos tengo y qué aprendí cuando no pude seguir funcionando igual.`,
  'Mi cuerpo': `Ejemplo: Mi cuerpo ha sido hogar, conflicto y memoria. Hay partes que acepto, otras que critiqué demasiado, y experiencias que cambiaron la forma en que me miro y me presento.`,
  'Mi mente': `Ejemplo: Mi mente puede ser mi aliada y mi cárcel. Pienso mucho, a veces demasiado, y escribiría cómo manejo mis ideas, mis obsesiones, mis intuiciones y mis momentos de claridad.`,
  'Mi rutina': `Ejemplo: Mi rutina muestra lo que realmente priorizo, no lo que digo priorizar. Hablaría de mis mañanas, mis distracciones, mis pequeños rituales y las partes de mi día que quiero cambiar.`,
  'Mi deporte': `Ejemplo: Mi deporte me conecta con disciplina, competencia o liberación. Contaría qué siento al entrenar, qué me ha enseñado sobre mi cuerpo y qué parte de mi carácter aparece cuando me exijo.`,
  'Mi arte': `Ejemplo: Mi arte es la forma en que saco algo que no siempre sé explicar. Puede ser dibujo, música, escritura o mirada; ahí aparece una sensibilidad que en otros contextos escondo.`,
  'Mi talento': `Ejemplo: Mi talento no siempre fue evidente para mí. Alguien lo notó antes, o apareció cuando insistí en algo que disfrutaba. Escribiría cómo lo uso y qué miedo tengo de desperdiciarlo.`,
  'Mi vicio': `Ejemplo: Mi vicio revela una forma de escapar. No lo contaría solo para confesarlo, sino para explicar qué vacío, ansiedad o placer intento calmar cuando vuelvo a eso.`,
  'Mi debilidad': `Ejemplo: Mi debilidad aparece cuando algo toca una herida precisa. Puede ser aprobación, abandono, orgullo o miedo; escribiría cómo me afecta y qué estoy intentando entender de esa reacción.`,
  'Mi fortaleza': `Ejemplo: Mi fortaleza no es que nada me duela, sino que he seguido incluso con miedo. Contaría una situación donde descubrí que podía resistir más de lo que imaginaba.`,
  'Mi yo deseado': `Ejemplo: Mi yo deseado es alguien más honesto, disciplinado y tranquilo. No quiero convertirme en otra persona, sino dejar de traicionarme en decisiones pequeñas que terminan definiendo mi vida.`,
  'Mi cuerpo deseado': `Ejemplo: Mi cuerpo deseado no es solo una imagen; es sentirme cómodo habitándolo. Quiero fuerza, salud y confianza, pero también dejar de tratarme como un proyecto que nunca está terminado.`,
  'Mi mente deseada': `Ejemplo: Mi mente deseada sería más clara y menos cruel conmigo. Me gustaría pensar con profundidad sin caer en ansiedad, decidir sin tanta culpa y descansar sin sentir que pierdo tiempo.`,
  'Mi vida deseada': `Ejemplo: Mi vida deseada tiene libertad, vínculos sinceros y días que no sienta que estoy sobreviviendo. Me imagino creando, amando y trabajando desde una calma que todavía estoy construyendo.`,
  'Mi propósito': `Ejemplo: Mi propósito parece aparecer cuando siento que lo que hago puede servirle a alguien más. No lo tengo completamente resuelto, pero sé que necesito crear algo con sentido.`,
  'Mi proyecto de vida': `Ejemplo: Mi proyecto de vida combina independencia, amor y construcción. Quiero una vida donde mis decisiones económicas, afectivas y creativas apunten en la misma dirección, aunque todavía esté aprendiendo cómo lograrlo.`,
  'Mi futuro': `Ejemplo: Mi futuro me emociona y me asusta. Hay días en que lo veo amplio y otros en que lo siento incierto, pero quiero llegar ahí sin abandonar las partes más verdaderas de mí.`,
  'Mi legado': `Ejemplo: Mi legado no tendría que ser fama; me bastaría dejar una huella honesta. Quiero que algunas personas recuerden que las cuidé, que creé algo útil o que viví con intención.`,
  'Mi relación con la ciencia': `Ejemplo: Mi relación con la ciencia mezcla curiosidad y respeto. Me interesa cómo explica lo que antes parecía misterio, aunque también me recuerda que muchas certezas pueden cambiar con nueva evidencia.`,
  'Mi relación con la historia': `Ejemplo: La historia me hace sentir que no nací en el vacío. Me interesa entender de dónde vienen las ideas, las heridas y las decisiones colectivas que todavía afectan mi vida.`,
  'Mi relación con la educación': `Ejemplo: La educación para mí ha sido oportunidad y también frustración. He aprendido en aulas, errores y conversaciones; por eso no reduzco la inteligencia a diplomas, aunque valore estudiar.`,
  'Mi relación con la medicina': `Ejemplo: La medicina me despierta gratitud y preguntas. He visto cómo puede aliviar, pero también cómo una persona enferma necesita ser escuchada, no tratada solo como un caso.`,
  'Mi relación con la tecnología': `Ejemplo: La tecnología me atrae porque amplifica capacidades, pero también me inquieta cuando reemplaza presencia o criterio. La uso, la disfruto y al mismo tiempo intento no entregarle toda mi atención.`,
  'Mi relación con la economía': `Ejemplo: La economía dejó de parecerme abstracta cuando entendí cómo afecta comida, tiempo y dignidad. Me interesa porque muestra qué valoramos realmente como sociedad, incluso cuando no lo admitimos.`,
  'Mi relación con la política': `Ejemplo: La política me importa porque decide cosas íntimas aunque parezcan lejanas. Me cuesta la manipulación, pero no quiero desentenderme de temas que afectan derechos, oportunidades y convivencia.`,
  'Mi relación con la religión': `Ejemplo: La religión en mi vida ha sido pregunta, herencia o refugio según la etapa. Hay símbolos que respeto, ideas que cuestiono y experiencias que me hicieron pensar en lo sagrado.`,
  'Mi relación con la geografía': `Ejemplo: La geografía me recuerda que el lugar donde nacemos cambia oportunidades, acentos, miedos y sueños. Me interesa cómo un territorio puede formar carácter sin que uno lo note.`,
  'Mi relación con la filosofía': `Ejemplo: La filosofía me acompaña cuando una respuesta práctica no basta. Me gusta porque obliga a preguntar por sentido, libertad, muerte y verdad, aunque a veces incomode vivir con tantas preguntas.`,
  'Mi relación con la psicología': `Ejemplo: La psicología me ayudó a mirar conductas que antes juzgaba sin entender. Me interesa porque revela patrones, heridas y formas de sanar que no siempre son visibles desde afuera.`,
  'Mi relación con el derecho': `Ejemplo: El derecho me parece una forma de ordenar conflictos humanos. Me interesa cuando protege al vulnerable, pero me inquieta cuando se vuelve lenguaje frío para injusticias muy reales.`,
  'Mi relación con las finanzas': `Ejemplo: Las finanzas me enseñan que libertad también requiere orden. Me interesa aprender a decidir mejor con el dinero, no para vivir obsesionado, sino para no depender siempre de la urgencia.`,
  'Mi relación con el emprendimiento': `Ejemplo: El emprendimiento me atrae porque combina riesgo, creatividad y carácter. Me entusiasma construir algo propio, aunque sé que también exige tolerar incertidumbre, ventas, errores y soledad.`,
  'Mi relación con el liderazgo': `Ejemplo: El liderazgo para mí no es mandar más fuerte. Admiro a quien da dirección sin humillar, escucha sin perder firmeza y sabe asumir responsabilidad cuando las cosas salen mal.`,
  'Mi relación con la comunicación': `Ejemplo: La comunicación me importa porque muchas heridas nacen de lo que no se dijo bien. Estoy aprendiendo a expresar límites, deseos y desacuerdos sin esconderme ni atacar.`,
  'Mi relación con el arte': `Ejemplo: El arte me conecta con emociones que no siempre caben en una explicación. Una canción, imagen o escena puede hacerme entender algo de mí antes de poder decirlo.`,
  'Mi relación con la música': `Ejemplo: La música ordena recuerdos que yo no sabía dónde guardar. Hay canciones que me devuelven a personas, etapas y versiones mías que todavía viven en algún lugar interno.`,
  'Mi relación con el deporte': `Ejemplo: El deporte me enseña disciplina y presencia. Cuando entreno o compito, aparecen mi paciencia, mi frustración y mi manera de medir progreso sin depender solo del resultado.`,
  'Mi relación con la gastronomía': `Ejemplo: La gastronomía para mí es memoria y encuentro. Un sabor puede llevarme a una casa, una persona o una etapa, y cocinar también puede ser una forma de cuidar.`,
  'Mi relación con la agricultura': `Ejemplo: La agricultura me conecta con paciencia, tierra y origen. Me recuerda que no todo crece al ritmo que uno quiere y que detrás de cada alimento hay trabajo invisible.`,
  'Mi relación con el medio ambiente': `Ejemplo: El medio ambiente me importa porque no es un tema lejano; es el aire, el agua y el futuro. A veces me siento incoherente, pero intento tomar más conciencia de mi impacto.`,
  'Mi relación con los idiomas': `Ejemplo: Los idiomas me atraen porque cada lengua abre una forma distinta de pensar. Aprender palabras nuevas me hace sentir que también puedo habitar otras culturas y versiones de mí.`,
  'Mi relación con la programación': `Ejemplo: La programación me gusta porque convierte ideas en herramientas. Me frustra cuando algo falla, pero también me emociona esa sensación de construir lógica que otra persona puede usar.`,
  'Mi relación con la inteligencia artificial': `Ejemplo: La inteligencia artificial me provoca fascinación y cautela. Veo posibilidades enormes para crear y aprender, pero también me pregunto qué partes humanas no deberíamos delegar sin pensar.`,
  'Mi relación con las inversiones': `Ejemplo: Las inversiones me interesan porque obligan a pensar en paciencia, riesgo y futuro. Estoy aprendiendo a no confundir ambición con apuestas impulsivas ni seguridad con miedo a crecer.`,
  'Mi mejor consejo': `Ejemplo: Mi mejor consejo sería no negociar tu paz para sostener una imagen. Lo aprendí tarde, después de intentar agradar, demostrar y permanecer en lugares donde ya no me reconocía.`,
  'Mi prototipo físico de pareja': `Ejemplo: Mi prototipo físico de pareja incluye rasgos que me atraen, pero no se reduce a medidas. Me importa una presencia, una forma de moverse y una energía que despierte deseo y calma.`,
  'Mi prototipo de personalidad de pareja': `Ejemplo: Mi prototipo de personalidad de pareja es alguien claro, curioso y afectivamente responsable. Me atrae la gente que sabe conversar, pedir perdón, sostener deseo y no convertir todo en competencia.`,
  'Mi comida': `Ejemplo: Mi comida favorita me conecta con recuerdos específicos. No es solo sabor; es una mesa, una persona, una etapa de mi vida y una sensación de hogar que aparece al probarla.`,
  'Mi música': `Ejemplo: Mi música dice mucho de mis estados internos. Hay canciones para mi tristeza, para mi ego, para mi deseo y para esos momentos en que necesito sentirme acompañado sin hablar.`,
  'Mi película': `Ejemplo: Mi película favorita me marcó porque vi algo mío en un personaje o una escena. Cada vez que la recuerdo, entiendo mejor un miedo, una esperanza o una forma de mirar la vida.`,
  'Mi serie': `Ejemplo: Mi serie favorita me atrapó porque sus personajes crecían, fallaban y se contradecían como personas reales. Creo que me gustó porque acompañó una etapa concreta de mi vida.`,
  'Mi libro': `Ejemplo: Mi libro favorito me encontró en un momento donde necesitaba palabras para algo que no sabía explicar. Lo recuerdo por una idea que me cambió la forma de entenderme.`,
  'Mi color': `Ejemplo: Mi color favorito tiene una emoción asociada. Lo elijo porque me transmite calma, fuerza, misterio o alegría, y de alguna manera siento que representa una parte de mi temperamento.`,
  'Mi estilo': `Ejemplo: Mi estilo muestra cómo quiero presentarme sin tener que explicarlo todo. A veces busco comodidad, otras impacto, y otras simplemente vestir una versión de mí que necesito sentir cerca.`,
  'Mi hogar': `Ejemplo: Mi hogar no es solo un lugar; es una sensación de seguridad. Lo imagino con ciertos olores, silencios, personas y rutinas que me permitan bajar la guardia.`,
  'Mi ciudad': `Ejemplo: Mi ciudad me formó con su ritmo, sus oportunidades y sus límites. Hay partes que amo, partes que critico y recuerdos que solo tienen sentido porque ocurrieron en esas calles.`,
  'Mi casa': `Ejemplo: Mi casa ideal tendría espacios donde pudiera descansar, crear y compartir sin sentir invasión. Más que lujo, quiero una casa que refleje calma, identidad y cierta libertad cotidiana.`,
  'Mi habitación': `Ejemplo: Mi habitación revela mi intimidad: lo que dejo a la vista, lo que escondo y cómo descanso. Es el lugar donde más se nota mi orden, mi caos y mi necesidad de refugio.`,
  'Mi mascota': `Ejemplo: Mi mascota me enseñó una forma de amor simple y constante. Hablaría de sus gestos, de cómo cambió mis días y de lo que me mostró sobre cuidado y compañía.`,
  'Mi proyecto': `Ejemplo: Mi proyecto representa una apuesta por algo que todavía no existe del todo. Me emociona porque mezcla esfuerzo, miedo y visión, y porque siento que ahí pongo una parte auténtica de mí.`,
  'Mi comunidad': `Ejemplo: Mi comunidad es el grupo donde siento pertenencia o deseo sentirla. Contaría qué compartimos, qué me aporta y qué responsabilidades aparecen cuando uno deja de pensar solo en sí mismo.`,
  'Mi invento': `Ejemplo: Mi invento sería una solución para algo que me ha molestado o dolido durante años. Lo imaginaría útil, humano y nacido de una necesidad que conozco de cerca.`,
  'Mi Dios': `Ejemplo: Mi Dios, si intento nombrarlo, no cabe del todo en una doctrina. Lo relaciono con presencia, misterio, justicia o consuelo, y también con preguntas que todavía no sé responder.`,
  'Mi Diablo': `Ejemplo: Mi Diablo representa aquello que me tienta, me divide o me empuja a traicionarme. No lo veo solo como mal externo, sino como una parte oscura que debo reconocer.`,
  'Mi bien': `Ejemplo: Mi bien está en las decisiones que me acercan a la paz y al cuidado. Para mí hacer el bien no siempre es agradar, a veces es decir una verdad incómoda.`,
  'Mi mal': `Ejemplo: Mi mal aparece cuando actúo desde resentimiento, ego o miedo. No me gusta admitirlo, pero sé que tengo sombras capaces de herir si no las miro con honestidad.`,
  'Mi creencia': `Ejemplo: Mi creencia más fuerte es que una persona puede cambiar si se mira sin mentirse. Esa idea me sostiene porque he visto cómo una decisión honesta puede romper patrones viejos.`,
  'Mi religión': `Ejemplo: Mi religión, o mi distancia con ella, está marcada por experiencias familiares, dudas y momentos de búsqueda. Hablaría de lo que conservo, lo que rechazo y lo que todavía me conmueve.`,
  'Mi política': `Ejemplo: Mi política nace de lo que considero justo y de lo que he visto faltar. No quiero repetir consignas; prefiero explicar qué experiencias formaron mi postura y qué contradicciones reconozco.`,
  'Mi ángel': `Ejemplo: Mi ángel sería esa parte de mí que intenta cuidar, perdonar y seguir creyendo. Aparece cuando alguien necesita ayuda o cuando decido no responder desde mi peor impulso.`,
  'Mi demonio': `Ejemplo: Mi demonio es la voz que exagera mi orgullo, mi deseo de control o mi rabia. No siempre gana, pero conocerlo me ayuda a no fingir que soy puro.`,
  'Mi pecado': `Ejemplo: Mi pecado tiene que ver con una tendencia que repito aunque sepa que me hace daño. Puede ser soberbia, deseo, evasión o silencio, y quiero entender qué busca proteger.`,
  'Mis ídolos': `Ejemplo: Mis ídolos muestran lo que admiro y lo que quisiera desarrollar en mí. No los veo perfectos; me interesan por su talento, valentía, disciplina o forma de sostener una visión.`,
}

const getWritingExample = (prompt) => {
  const example =
    writingExamples[prompt] ??
    `Ejemplo: Escribiría una experiencia concreta relacionada con ${prompt.toLocaleLowerCase('es-CO')}, explicando qué pasó, cómo me marcó y qué revela de mí hoy.`

  return example.endsWith('...')
    ? example
    : `${example.replace(/\.+$/, '')}...`
}

const createQuestion = (prompt, index) => ({
  id: index + 1,
  key: `Revelación:${prompt}`,
  category: 'Revelación',
  prompt,
  suggestedPrice: '0.10',
  writingExample: getWritingExample(prompt),
  minWords: 100,
  maxWords: 2000,
  maxCharacters: 12000,
  fields,
})

export const questions = prompts.map(createQuestion)

export const getQuestion = (id) =>
  questions.find((question) => question.id === Number(id))
