const prompts = [
  'Mi autobiografía',
  'Yo en 3 años',
  'Yo en 5 años',
  'Yo en 10 años',
  'Mis fantasias sociales',
  'Mis fantasias espirituales',
  'Mis fantasias profesionales',
  'Mis fantasias economicas',
  'Mis fantasias romanticas',
  'Mis fantasias sexuales',
  'Mis fetiches',
  'Mi infancia',
  'Mi adolescencia',
  'Mi adultez',
  'Mi primera cita',
  'Mi última cita',
  'Mi mejor cita',
  'Mi peor cita',
  'Mi peor error',
  'Mi acierto',
  'Mi fracaso',
  'Mi logro',
  'Mi arrepentimiento',
  'Mis viajes',
  'Mis empleos',
  'Mis aventuras',
  'Mis fiestas',
  'Mis pérdidas',
  'Mis desafíos',
  'Mis mudanzas',
  'Mis miedos',
  'Mis deseos',
  'Mis principios económicos',
  'Mis principios sexuales',
  'Mis principios sociales',
  'Mis principios emocionales',
  'Mis límites económicos',
  'Mis límites sexuales',
  'Mis límites sociales',
  'Mis límites emocionales',
  'Mi decisión más difícil',
  'Mi decisión de la que más orgulloso estoy',
  'Mi renuncia',
  'Mi sacrificio',
  'Mi mayor cambio',
  'Mi punto de quiebre',
  'Mi pareja',
  'Mis parejas',
  'Mis exparejas',
  'Mi expareja que más extraño',
  'Mi amante',
  'Mi enemigo',
  'Mi rival',
  'Mi crush',
  'Mi admirador',
  'Mi amor imposible',
  'Mi confidente',
  'Mi cómplice',
  'Mi persona favorita',
  'Mi terapeuta',
  'Mi mamá',
  'Mi papá',
  'Mis hijos',
  'Mis hijas',
  'Mis hermanos',
  'Mis hermanas',
  'Mis abuelos',
  'Mis abuelas',
  'Mis tíos',
  'Mis tías',
  'Mis primos',
  'Mis primas',
  'Mi suegro',
  'Mi suegra',
  'Mis cuñados',
  'Mis cuñadas',
  'Mi mejor amigo',
  'Mi mejor amiga',
  'Mis amigos',
  'Mis amigas',
  'Mis vecinos',
  'Mis vecinas',
  'Mi jefe',
  'Mi líder',
  'Mis socios',
  'Mis socias',
  'Mis empleados',
  'Mis empleadas',
  'Mis clientes',
  'Mis clientas',
  'Mis compañeros de trabajo',
  'Mis compañeras de trabajo',
  'Mis profesores',
  'Mis profesoras',
  'Mis alumnos',
  'Mis alumnas',
  'Mis mentores',
  'Mis mentoras',
  'Mi sexualidad',
  'Mi dinero',
  'Mi fidelidad',
  'Mi familia',
  'Mi trabajo',
  'Mi salud',
  'Mi cuerpo',
  'Mi mente',
  'Mi rutina',
  'Mi deporte',
  'Mi arte',
  'Mi talento',
  'Mi vicio',
  'Mi debilidad',
  'Mi fortaleza',
  'Mi yo deseado',
  'Mi cuerpo deseado',
  'Mi mente deseada',
  'Mi vida deseada',
  'Mi propósito',
  'Mi proyecto de vida',
  'Mi futuro',
  'Mi legado',
  'Mi relación con la ciencia',
  'Mi relación con la historia',
  'Mi relación con la educación',
  'Mi relación con la medicina',
  'Mi relación con la tecnología',
  'Mi relación con la economía',
  'Mi relación con la política',
  'Mi relación con la religión',
  'Mi relación con la geografía',
  'Mi relación con la filosofía',
  'Mi relación con la psicología',
  'Mi relación con el derecho',
  'Mi relación con las finanzas',
  'Mi relación con el emprendimiento',
  'Mi relación con el liderazgo',
  'Mi relación con la comunicación',
  'Mi relación con el arte',
  'Mi relación con la música',
  'Mi relación con el deporte',
  'Mi relación con la gastronomía',
  'Mi relación con la agricultura',
  'Mi relación con el medio ambiente',
  'Mi relación con los idiomas',
  'Mi relación con la programación',
  'Mi relación con la inteligencia artificial',
  'Mi relación con las inversiones',
  'Mi mejor consejo',
  'Mi prototipo físico de pareja',
  'Mi prototipo de personalidad de pareja',
  'Mi comida',
  'Mi música',
  'Mi película',
  'Mi serie',
  'Mi libro',
  'Mi color',
  'Mi estilo',
  'Mi hogar',
  'Mi ciudad',
  'Mi casa',
  'Mi habitación',
  'Mi mascota',
  'Mi proyecto',
  'Mi comunidad',
  'Mi invento',
  'Mi Dios',
  'Mi Diablo',
  'Mi bien',
  'Mi mal',
  'Mi creencia',
  'Mi religión',
  'Mi política',
  'Mi ángel',
  'Mi demonio',
  'Mi pecado',
  'Mis ídolos',
]

const fields = [
  {
    key: 'revelation',
    label: 'Redacción personal',
    type: 'textarea',
    placeholder: 'Escribe tu revelación personal sobre esta tarjeta',
  },
]

const createQuestion = (prompt, index) => ({
  id: index + 1,
  key: `Revelación:${prompt}`,
  category: 'Revelación',
  prompt,
  suggestedPrice: '0.10',
  minWords: 100,
  maxWords: 2000,
  maxCharacters: 12000,
  fields,
})

export const questions = prompts.map(createQuestion)

export const getQuestion = (id) =>
  questions.find((question) => question.id === Number(id))
